// Cross-reference data for production flow diagram traceability
// Maps node IDs to diagrams, metadata, and ficha técnica URLs

const CROSS_REF = {
  // Node ID → [{d: diagram filename, p: product name, f: family}]
  presenteEn: {
    'bolsa': [
      {d: 'dark_salsa_boletus.html', p: 'Salsa Boletus', f: 'Salsas'},
      {d: 'dark_salsa_iberica.html', p: 'Salsa Ibérico', f: 'Salsas'},
      {d: 'dark_salsa_negra.html', p: 'Salsa Negra', f: 'Salsas'},
      {d: 'dark_salsa_pescado.html', p: 'Salsa Pescado', f: 'Salsas'},
      {d: 'dark_salsa_pollo.html', p: 'Salsa Pollo', f: 'Salsas'},
      {d: 'dark_salsa_queso.html', p: 'Salsa Queso', f: 'Salsas'},
      {d: 'dark_salsa_tartufata.html', p: 'Salsa Tartufata', f: 'Salsas'},
      {d: 'dark_salsa_verduras.html', p: 'Salsa Verduras', f: 'Salsas'},
    ],
    'cajaRis': [
      {d: 'dark_salsa_boletus.html', p: 'Salsa Boletus', f: 'Salsas'},
      {d: 'dark_salsa_iberica.html', p: 'Salsa Ibérico', f: 'Salsas'},
      {d: 'dark_salsa_negra.html', p: 'Salsa Negra', f: 'Salsas'},
      {d: 'dark_salsa_pescado.html', p: 'Salsa Pescado', f: 'Salsas'},
      {d: 'dark_salsa_pollo.html', p: 'Salsa Pollo', f: 'Salsas'},
      {d: 'dark_salsa_queso.html', p: 'Salsa Queso', f: 'Salsas'},
      {d: 'dark_salsa_tartufata.html', p: 'Salsa Tartufata', f: 'Salsas'},
      {d: 'dark_salsa_verduras.html', p: 'Salsa Verduras', f: 'Salsas'},
    ],
    'calN': [
      {d: 'dark_negro.html', p: 'Arroz Negro', f: 'La Santa'},
    ],
    'calP': [
      {d: 'dark_pescado.html', p: 'Arroz Pescado', f: 'La Santa'},
    ],
    'calPo': [
      {d: 'dark_pollo.html', p: 'Arroz Pollo', f: 'La Santa'},
    ],
    'calR': [
      {d: 'dark_cremoso_iberico.html', p: 'Cremoso Ibérico', f: 'All-Included'},
      {d: 'dark_cremoso_queso.html', p: 'Cremoso Queso', f: 'All-Included'},
      {d: 'dark_cremoso_setas.html', p: 'Cremoso Setas', f: 'All-Included'},
      {d: 'dark_cremoso_tartufato.html', p: 'Cremoso Tartufato', f: 'All-Included'},
      {d: 'dark_risotto.html', p: 'Risotto', f: 'La Santa'},
    ],
    'calV': [
      {d: 'dark_verduras.html', p: 'Arroz Verduras', f: 'La Santa'},
    ],
    'jarP': [
      {d: 'dark_negro.html', p: 'Arroz Negro', f: 'La Santa'},
      {d: 'dark_pescado.html', p: 'Arroz Pescado', f: 'La Santa'},
      {d: 'dark_pollo.html', p: 'Arroz Pollo', f: 'La Santa'},
    ],
    'jarR': [
      {d: 'dark_cremoso_iberico.html', p: 'Cremoso Ibérico', f: 'All-Included'},
      {d: 'dark_cremoso_queso.html', p: 'Cremoso Queso', f: 'All-Included'},
      {d: 'dark_cremoso_setas.html', p: 'Cremoso Setas', f: 'All-Included'},
      {d: 'dark_cremoso_tartufato.html', p: 'Cremoso Tartufato', f: 'All-Included'},
      {d: 'dark_risotto.html', p: 'Risotto', f: 'La Santa'},
    ],
    'jarV': [
      {d: 'dark_verduras.html', p: 'Arroz Verduras', f: 'La Santa'},
    ],
    'mezJ': [
      {d: 'dark_negro.html', p: 'Arroz Negro', f: 'La Santa'},
      {d: 'dark_pescado.html', p: 'Arroz Pescado', f: 'La Santa'},
      {d: 'dark_pollo.html', p: 'Arroz Pollo', f: 'La Santa'},
      {d: 'dark_verduras.html', p: 'Arroz Verduras', f: 'La Santa'},
    ],
    'mezJM': [
      {d: 'dark_maestro.html', p: 'Maestro', f: 'Maestro'},
    ],
    'mezJR': [
      {d: 'dark_cremoso_iberico.html', p: 'Cremoso Ibérico', f: 'All-Included'},
      {d: 'dark_cremoso_queso.html', p: 'Cremoso Queso', f: 'All-Included'},
      {d: 'dark_cremoso_setas.html', p: 'Cremoso Setas', f: 'All-Included'},
      {d: 'dark_cremoso_tartufato.html', p: 'Cremoso Tartufato', f: 'All-Included'},
    ],
    'mezR': [
      {d: 'dark_risotto.html', p: 'Risotto', f: 'La Santa'},
    ],
    'mp01': [
      {d: 'dark_negro.html', p: 'Arroz Negro', f: 'La Santa'},
      {d: 'dark_pescado.html', p: 'Arroz Pescado', f: 'La Santa'},
    ],
    'mp03': [
      {d: 'dark_pollo.html', p: 'Arroz Pollo', f: 'La Santa'},
    ],
    'mp04': [
      {d: 'dark_cremoso_iberico.html', p: 'Cremoso Ibérico', f: 'All-Included'},
      {d: 'dark_cremoso_queso.html', p: 'Cremoso Queso', f: 'All-Included'},
      {d: 'dark_cremoso_setas.html', p: 'Cremoso Setas', f: 'All-Included'},
      {d: 'dark_cremoso_tartufato.html', p: 'Cremoso Tartufato', f: 'All-Included'},
      {d: 'dark_negro.html', p: 'Arroz Negro', f: 'La Santa'},
      {d: 'dark_pescado.html', p: 'Arroz Pescado', f: 'La Santa'},
      {d: 'dark_pollo.html', p: 'Arroz Pollo', f: 'La Santa'},
      {d: 'dark_risotto.html', p: 'Risotto', f: 'La Santa'},
      {d: 'dark_salsa_boletus.html', p: 'Salsa Boletus', f: 'Salsas'},
      {d: 'dark_verduras.html', p: 'Arroz Verduras', f: 'La Santa'},
    ],
    'mp05': [
      {d: 'dark_pollo.html', p: 'Arroz Pollo', f: 'La Santa'},
      {d: 'dark_verduras.html', p: 'Arroz Verduras', f: 'La Santa'},
    ],
    'mp06': [
      {d: 'dark_cremoso_iberico.html', p: 'Cremoso Ibérico', f: 'All-Included'},
      {d: 'dark_cremoso_queso.html', p: 'Cremoso Queso', f: 'All-Included'},
      {d: 'dark_cremoso_setas.html', p: 'Cremoso Setas', f: 'All-Included'},
      {d: 'dark_cremoso_tartufato.html', p: 'Cremoso Tartufato', f: 'All-Included'},
      {d: 'dark_maestro.html', p: 'Maestro', f: 'Maestro'},
      {d: 'dark_negro.html', p: 'Arroz Negro', f: 'La Santa'},
      {d: 'dark_pescado.html', p: 'Arroz Pescado', f: 'La Santa'},
      {d: 'dark_pollo.html', p: 'Arroz Pollo', f: 'La Santa'},
      {d: 'dark_risotto.html', p: 'Risotto', f: 'La Santa'},
      {d: 'dark_salsa_boletus.html', p: 'Salsa Boletus', f: 'Salsas'},
      {d: 'dark_verduras.html', p: 'Arroz Verduras', f: 'La Santa'},
    ],
    'mp07': [
      {d: 'dark_cremoso_iberico.html', p: 'Cremoso Ibérico', f: 'All-Included'},
      {d: 'dark_cremoso_queso.html', p: 'Cremoso Queso', f: 'All-Included'},
      {d: 'dark_cremoso_setas.html', p: 'Cremoso Setas', f: 'All-Included'},
      {d: 'dark_cremoso_tartufato.html', p: 'Cremoso Tartufato', f: 'All-Included'},
      {d: 'dark_negro.html', p: 'Arroz Negro', f: 'La Santa'},
      {d: 'dark_pescado.html', p: 'Arroz Pescado', f: 'La Santa'},
      {d: 'dark_pollo.html', p: 'Arroz Pollo', f: 'La Santa'},
      {d: 'dark_risotto.html', p: 'Risotto', f: 'La Santa'},
      {d: 'dark_salsa_boletus.html', p: 'Salsa Boletus', f: 'Salsas'},
      {d: 'dark_verduras.html', p: 'Arroz Verduras', f: 'La Santa'},
    ],
    'mp08': [
      {d: 'dark_negro.html', p: 'Arroz Negro', f: 'La Santa'},
    ],
    'mp09': [
      {d: 'dark_cremoso_iberico.html', p: 'Cremoso Ibérico', f: 'All-Included'},
      {d: 'dark_cremoso_queso.html', p: 'Cremoso Queso', f: 'All-Included'},
      {d: 'dark_cremoso_setas.html', p: 'Cremoso Setas', f: 'All-Included'},
      {d: 'dark_cremoso_tartufato.html', p: 'Cremoso Tartufato', f: 'All-Included'},
      {d: 'dark_maestro.html', p: 'Maestro', f: 'Maestro'},
      {d: 'dark_negro.html', p: 'Arroz Negro', f: 'La Santa'},
      {d: 'dark_pescado.html', p: 'Arroz Pescado', f: 'La Santa'},
      {d: 'dark_pollo.html', p: 'Arroz Pollo', f: 'La Santa'},
      {d: 'dark_risotto.html', p: 'Risotto', f: 'La Santa'},
      {d: 'dark_salsa_boletus.html', p: 'Salsa Boletus', f: 'Salsas'},
      {d: 'dark_verduras.html', p: 'Arroz Verduras', f: 'La Santa'},
    ],
    'mp10': [
      {d: 'dark_pescado.html', p: 'Arroz Pescado', f: 'La Santa'},
      {d: 'dark_verduras.html', p: 'Arroz Verduras', f: 'La Santa'},
    ],
    'mp11': [
      {d: 'dark_verduras.html', p: 'Arroz Verduras', f: 'La Santa'},
    ],
    'mp12': [
      {d: 'dark_risotto.html', p: 'Risotto', f: 'La Santa'},
    ],
    'mp13': [
      {d: 'dark_cremoso_iberico.html', p: 'Cremoso Ibérico', f: 'All-Included'},
      {d: 'dark_cremoso_queso.html', p: 'Cremoso Queso', f: 'All-Included'},
      {d: 'dark_cremoso_setas.html', p: 'Cremoso Setas', f: 'All-Included'},
      {d: 'dark_cremoso_tartufato.html', p: 'Cremoso Tartufato', f: 'All-Included'},
      {d: 'dark_risotto.html', p: 'Risotto', f: 'La Santa'},
    ],
    'mp19': [
      {d: 'dark_maestro.html', p: 'Maestro', f: 'Maestro'},
      {d: 'dark_pescado.html', p: 'Arroz Pescado', f: 'La Santa'},
      {d: 'dark_pollo.html', p: 'Arroz Pollo', f: 'La Santa'},
      {d: 'dark_verduras.html', p: 'Arroz Verduras', f: 'La Santa'},
    ],
    'mp21': [
      {d: 'dark_salsa_boletus.html', p: 'Salsa Boletus', f: 'Salsas'},
    ],
    'mp22': [
      {d: 'dark_cremoso_setas.html', p: 'Cremoso Setas', f: 'All-Included'},
    ],
    'mp23': [
      {d: 'dark_cremoso_tartufato.html', p: 'Cremoso Tartufato', f: 'All-Included'},
    ],
    'mp31': [
      {d: 'dark_pescado.html', p: 'Arroz Pescado', f: 'La Santa'},
    ],
    'mp33': [
      {d: 'dark_negro.html', p: 'Arroz Negro', f: 'La Santa'},
      {d: 'dark_pescado.html', p: 'Arroz Pescado', f: 'La Santa'},
      {d: 'dark_pollo.html', p: 'Arroz Pollo', f: 'La Santa'},
      {d: 'dark_verduras.html', p: 'Arroz Verduras', f: 'La Santa'},
    ],
    'mp34': [
      {d: 'dark_risotto.html', p: 'Risotto', f: 'La Santa'},
      {d: 'dark_verduras.html', p: 'Arroz Verduras', f: 'La Santa'},
    ],
    'mp35': [
      {d: 'dark_cremoso_iberico.html', p: 'Cremoso Ibérico', f: 'All-Included'},
      {d: 'dark_cremoso_queso.html', p: 'Cremoso Queso', f: 'All-Included'},
      {d: 'dark_cremoso_setas.html', p: 'Cremoso Setas', f: 'All-Included'},
      {d: 'dark_cremoso_tartufato.html', p: 'Cremoso Tartufato', f: 'All-Included'},
      {d: 'dark_negro.html', p: 'Arroz Negro', f: 'La Santa'},
      {d: 'dark_pescado.html', p: 'Arroz Pescado', f: 'La Santa'},
      {d: 'dark_pollo.html', p: 'Arroz Pollo', f: 'La Santa'},
      {d: 'dark_risotto.html', p: 'Risotto', f: 'La Santa'},
    ],
    'mp36': [
      {d: 'dark_risotto.html', p: 'Risotto', f: 'La Santa'},
      {d: 'dark_verduras.html', p: 'Arroz Verduras', f: 'La Santa'},
    ],
    'mp38': [
      {d: 'dark_maestro.html', p: 'Maestro', f: 'Maestro'},
      {d: 'dark_risotto.html', p: 'Risotto', f: 'La Santa'},
    ],
    'mp39': [
      {d: 'dark_risotto.html', p: 'Risotto', f: 'La Santa'},
    ],
    'mp52': [
      {d: 'dark_maestro.html', p: 'Maestro', f: 'Maestro'},
    ],
    'mp53': [
      {d: 'dark_maestro.html', p: 'Maestro', f: 'Maestro'},
    ],
    'mp65': [
      {d: 'dark_salsa_boletus.html', p: 'Salsa Boletus', f: 'Salsas'},
    ],
    'mp66': [
      {d: 'dark_salsa_boletus.html', p: 'Salsa Boletus', f: 'Salsas'},
    ],
    'mp73': [
      {d: 'dark_cremoso_queso.html', p: 'Cremoso Queso', f: 'All-Included'},
    ],
    'mpAceite': [
      {d: 'dark_salsa_iberica.html', p: 'Salsa Ibérico', f: 'Salsas'},
      {d: 'dark_salsa_queso.html', p: 'Salsa Queso', f: 'Salsas'},
      {d: 'dark_salsa_tartufata.html', p: 'Salsa Tartufata', f: 'Salsas'},
    ],
    'mpAceiteTrufado': [
      {d: 'dark_salsa_tartufata.html', p: 'Salsa Tartufata', f: 'Salsas'},
    ],
    'mpAg': [
      {d: 'dark_cremoso_iberico.html', p: 'Cremoso Ibérico', f: 'All-Included'},
      {d: 'dark_cremoso_queso.html', p: 'Cremoso Queso', f: 'All-Included'},
      {d: 'dark_cremoso_setas.html', p: 'Cremoso Setas', f: 'All-Included'},
      {d: 'dark_cremoso_tartufato.html', p: 'Cremoso Tartufato', f: 'All-Included'},
      {d: 'dark_maestro.html', p: 'Maestro', f: 'Maestro'},
      {d: 'dark_negro.html', p: 'Arroz Negro', f: 'La Santa'},
      {d: 'dark_pescado.html', p: 'Arroz Pescado', f: 'La Santa'},
      {d: 'dark_pollo.html', p: 'Arroz Pollo', f: 'La Santa'},
      {d: 'dark_risotto.html', p: 'Risotto', f: 'La Santa'},
      {d: 'dark_salsa_boletus.html', p: 'Salsa Boletus', f: 'Salsas'},
      {d: 'dark_verduras.html', p: 'Arroz Verduras', f: 'La Santa'},
    ],
    'mpAgua': [
      {d: 'dark_salsa_iberica.html', p: 'Salsa Ibérico', f: 'Salsas'},
      {d: 'dark_salsa_pescado.html', p: 'Salsa Pescado', f: 'Salsas'},
      {d: 'dark_salsa_pollo.html', p: 'Salsa Pollo', f: 'Salsas'},
      {d: 'dark_salsa_queso.html', p: 'Salsa Queso', f: 'Salsas'},
      {d: 'dark_salsa_tartufata.html', p: 'Salsa Tartufata', f: 'Salsas'},
    ],
    'mpAgua1': [
      {d: 'dark_salsa_verduras.html', p: 'Salsa Verduras', f: 'Salsas'},
    ],
    'mpAguaAlmidonada': [
      {d: 'dark_salsa_verduras.html', p: 'Salsa Verduras', f: 'Salsas'},
    ],
    'mpAjo': [
      {d: 'dark_cremoso_iberico.html', p: 'Cremoso Ibérico', f: 'All-Included'},
      {d: 'dark_cremoso_queso.html', p: 'Cremoso Queso', f: 'All-Included'},
      {d: 'dark_cremoso_setas.html', p: 'Cremoso Setas', f: 'All-Included'},
      {d: 'dark_cremoso_tartufato.html', p: 'Cremoso Tartufato', f: 'All-Included'},
      {d: 'dark_negro.html', p: 'Arroz Negro', f: 'La Santa'},
      {d: 'dark_pescado.html', p: 'Arroz Pescado', f: 'La Santa'},
      {d: 'dark_pollo.html', p: 'Arroz Pollo', f: 'La Santa'},
      {d: 'dark_risotto.html', p: 'Risotto', f: 'La Santa'},
      {d: 'dark_verduras.html', p: 'Arroz Verduras', f: 'La Santa'},
    ],
    'mpAromaJamon': [
      {d: 'dark_salsa_iberica.html', p: 'Salsa Ibérico', f: 'Salsas'},
    ],
    'mpAromaQue': [
      {d: 'dark_cremoso_queso.html', p: 'Cremoso Queso', f: 'All-Included'},
    ],
    'mpAromaQueso': [
      {d: 'dark_salsa_queso.html', p: 'Salsa Queso', f: 'Salsas'},
    ],
    'mpBand': [
      {d: 'dark_cremoso_iberico.html', p: 'Cremoso Ibérico', f: 'All-Included'},
      {d: 'dark_cremoso_queso.html', p: 'Cremoso Queso', f: 'All-Included'},
      {d: 'dark_cremoso_setas.html', p: 'Cremoso Setas', f: 'All-Included'},
      {d: 'dark_cremoso_tartufato.html', p: 'Cremoso Tartufato', f: 'All-Included'},
      {d: 'dark_maestro.html', p: 'Maestro', f: 'Maestro'},
      {d: 'dark_negro.html', p: 'Arroz Negro', f: 'La Santa'},
      {d: 'dark_pescado.html', p: 'Arroz Pescado', f: 'La Santa'},
      {d: 'dark_pollo.html', p: 'Arroz Pollo', f: 'La Santa'},
      {d: 'dark_risotto.html', p: 'Risotto', f: 'La Santa'},
      {d: 'dark_verduras.html', p: 'Arroz Verduras', f: 'La Santa'},
    ],
    'mpCMC': [
      {d: 'dark_salsa_iberica.html', p: 'Salsa Ibérico', f: 'Salsas'},
      {d: 'dark_salsa_queso.html', p: 'Salsa Queso', f: 'Salsas'},
    ],
    'mpCaldoPescado': [
      {d: 'dark_salsa_negra.html', p: 'Salsa Negra', f: 'Salsas'},
      {d: 'dark_salsa_pescado.html', p: 'Salsa Pescado', f: 'Salsas'},
    ],
    'mpCaldoPollo': [
      {d: 'dark_salsa_pollo.html', p: 'Salsa Pollo', f: 'Salsas'},
    ],
    'mpCeb': [
      {d: 'dark_salsa_boletus.html', p: 'Salsa Boletus', f: 'Salsas'},
      {d: 'dark_salsa_tartufata.html', p: 'Salsa Tartufata', f: 'Salsas'},
    ],
    'mpCur': [
      {d: 'dark_pescado.html', p: 'Arroz Pescado', f: 'La Santa'},
    ],
    'mpFilm': [
      {d: 'dark_cremoso_iberico.html', p: 'Cremoso Ibérico', f: 'All-Included'},
      {d: 'dark_cremoso_queso.html', p: 'Cremoso Queso', f: 'All-Included'},
      {d: 'dark_cremoso_setas.html', p: 'Cremoso Setas', f: 'All-Included'},
      {d: 'dark_cremoso_tartufato.html', p: 'Cremoso Tartufato', f: 'All-Included'},
      {d: 'dark_maestro.html', p: 'Maestro', f: 'Maestro'},
      {d: 'dark_negro.html', p: 'Arroz Negro', f: 'La Santa'},
      {d: 'dark_pescado.html', p: 'Arroz Pescado', f: 'La Santa'},
      {d: 'dark_pollo.html', p: 'Arroz Pollo', f: 'La Santa'},
      {d: 'dark_risotto.html', p: 'Risotto', f: 'La Santa'},
      {d: 'dark_salsa_boletus.html', p: 'Salsa Boletus', f: 'Salsas'},
      {d: 'dark_salsa_iberica.html', p: 'Salsa Ibérico', f: 'Salsas'},
      {d: 'dark_salsa_negra.html', p: 'Salsa Negra', f: 'Salsas'},
      {d: 'dark_salsa_pescado.html', p: 'Salsa Pescado', f: 'Salsas'},
      {d: 'dark_salsa_pollo.html', p: 'Salsa Pollo', f: 'Salsas'},
      {d: 'dark_salsa_queso.html', p: 'Salsa Queso', f: 'Salsas'},
      {d: 'dark_salsa_tartufata.html', p: 'Salsa Tartufata', f: 'Salsas'},
      {d: 'dark_salsa_verduras.html', p: 'Salsa Verduras', f: 'Salsas'},
      {d: 'dark_verduras.html', p: 'Arroz Verduras', f: 'La Santa'},
    ],
    'mpGraPollo': [
      {d: 'dark_cremoso_queso.html', p: 'Cremoso Queso', f: 'All-Included'},
    ],
    'mpGrasaPollo': [
      {d: 'dark_salsa_iberica.html', p: 'Salsa Ibérico', f: 'Salsas'},
      {d: 'dark_salsa_queso.html', p: 'Salsa Queso', f: 'Salsas'},
      {d: 'dark_salsa_tartufata.html', p: 'Salsa Tartufata', f: 'Salsas'},
    ],
    'mpHazelnut': [
      {d: 'dark_salsa_pollo.html', p: 'Salsa Pollo', f: 'Salsas'},
      {d: 'dark_salsa_tartufata.html', p: 'Salsa Tartufata', f: 'Salsas'},
    ],
    'mpJamon': [
      {d: 'dark_cremoso_iberico.html', p: 'Cremoso Ibérico', f: 'All-Included'},
    ],
    'mpJerez': [
      {d: 'dark_salsa_queso.html', p: 'Salsa Queso', f: 'Salsas'},
    ],
    'mpMant': [
      {d: 'dark_salsa_boletus.html', p: 'Salsa Boletus', f: 'Salsas'},
      {d: 'dark_salsa_queso.html', p: 'Salsa Queso', f: 'Salsas'},
      {d: 'dark_salsa_tartufata.html', p: 'Salsa Tartufata', f: 'Salsas'},
    ],
    'mpManzanilla': [
      {d: 'dark_salsa_iberica.html', p: 'Salsa Ibérico', f: 'Salsas'},
    ],
    'mpNata': [
      {d: 'dark_salsa_iberica.html', p: 'Salsa Ibérico', f: 'Salsas'},
      {d: 'dark_salsa_queso.html', p: 'Salsa Queso', f: 'Salsas'},
    ],
    'mpParm': [
      {d: 'dark_salsa_boletus.html', p: 'Salsa Boletus', f: 'Salsas'},
      {d: 'dark_salsa_tartufata.html', p: 'Salsa Tartufata', f: 'Salsas'},
    ],
    'mpPimienta': [
      {d: 'dark_salsa_queso.html', p: 'Salsa Queso', f: 'Salsas'},
    ],
    'mpQuesoAzul': [
      {d: 'dark_salsa_queso.html', p: 'Salsa Queso', f: 'Salsas'},
    ],
    'mpSal': [
      {d: 'dark_cremoso_iberico.html', p: 'Cremoso Ibérico', f: 'All-Included'},
      {d: 'dark_cremoso_queso.html', p: 'Cremoso Queso', f: 'All-Included'},
      {d: 'dark_cremoso_setas.html', p: 'Cremoso Setas', f: 'All-Included'},
      {d: 'dark_cremoso_tartufato.html', p: 'Cremoso Tartufato', f: 'All-Included'},
      {d: 'dark_negro.html', p: 'Arroz Negro', f: 'La Santa'},
      {d: 'dark_pescado.html', p: 'Arroz Pescado', f: 'La Santa'},
      {d: 'dark_pollo.html', p: 'Arroz Pollo', f: 'La Santa'},
      {d: 'dark_risotto.html', p: 'Risotto', f: 'La Santa'},
      {d: 'dark_salsa_boletus.html', p: 'Salsa Boletus', f: 'Salsas'},
      {d: 'dark_salsa_iberica.html', p: 'Salsa Ibérico', f: 'Salsas'},
      {d: 'dark_salsa_negra.html', p: 'Salsa Negra', f: 'Salsas'},
      {d: 'dark_salsa_pescado.html', p: 'Salsa Pescado', f: 'Salsas'},
      {d: 'dark_salsa_pollo.html', p: 'Salsa Pollo', f: 'Salsas'},
      {d: 'dark_salsa_queso.html', p: 'Salsa Queso', f: 'Salsas'},
      {d: 'dark_salsa_tartufata.html', p: 'Salsa Tartufata', f: 'Salsas'},
      {d: 'dark_verduras.html', p: 'Arroz Verduras', f: 'La Santa'},
    ],
    'mpSalmorreta': [
      {d: 'dark_salsa_negra.html', p: 'Salsa Negra', f: 'Salsas'},
      {d: 'dark_salsa_pescado.html', p: 'Salsa Pescado', f: 'Salsas'},
      {d: 'dark_salsa_pollo.html', p: 'Salsa Pollo', f: 'Salsas'},
    ],
    'mpSalsaVerd': [
      {d: 'dark_salsa_verduras.html', p: 'Salsa Verduras', f: 'Salsas'},
    ],
    'mpTinta': [
      {d: 'dark_salsa_negra.html', p: 'Salsa Negra', f: 'Salsas'},
    ],
    'mpUmami': [
      {d: 'dark_salsa_iberica.html', p: 'Salsa Ibérico', f: 'Salsas'},
      {d: 'dark_salsa_pollo.html', p: 'Salsa Pollo', f: 'Salsas'},
      {d: 'dark_salsa_queso.html', p: 'Salsa Queso', f: 'Salsas'},
      {d: 'dark_salsa_tartufata.html', p: 'Salsa Tartufata', f: 'Salsas'},
    ],
    'mpVino': [
      {d: 'dark_salsa_tartufata.html', p: 'Salsa Tartufata', f: 'Salsas'},
    ],
    'mpXantana': [
      {d: 'dark_salsa_iberica.html', p: 'Salsa Ibérico', f: 'Salsas'},
      {d: 'dark_salsa_queso.html', p: 'Salsa Queso', f: 'Salsas'},
      {d: 'dark_salsa_tartufata.html', p: 'Salsa Tartufata', f: 'Salsas'},
    ],
    'preAjo': [
      {d: 'dark_cremoso_iberico.html', p: 'Cremoso Ibérico', f: 'All-Included'},
      {d: 'dark_cremoso_queso.html', p: 'Cremoso Queso', f: 'All-Included'},
      {d: 'dark_cremoso_setas.html', p: 'Cremoso Setas', f: 'All-Included'},
      {d: 'dark_cremoso_tartufato.html', p: 'Cremoso Tartufato', f: 'All-Included'},
      {d: 'dark_negro.html', p: 'Arroz Negro', f: 'La Santa'},
      {d: 'dark_pescado.html', p: 'Arroz Pescado', f: 'La Santa'},
      {d: 'dark_pollo.html', p: 'Arroz Pollo', f: 'La Santa'},
      {d: 'dark_risotto.html', p: 'Risotto', f: 'La Santa'},
      {d: 'dark_verduras.html', p: 'Arroz Verduras', f: 'La Santa'},
    ],
    'preAjoM': [
      {d: 'dark_maestro.html', p: 'Maestro', f: 'Maestro'},
    ],
    'preAz': [
      {d: 'dark_maestro.html', p: 'Maestro', f: 'Maestro'},
      {d: 'dark_pescado.html', p: 'Arroz Pescado', f: 'La Santa'},
      {d: 'dark_pollo.html', p: 'Arroz Pollo', f: 'La Santa'},
      {d: 'dark_verduras.html', p: 'Arroz Verduras', f: 'La Santa'},
    ],
    'preNora': [
      {d: 'dark_pescado.html', p: 'Arroz Pescado', f: 'La Santa'},
    ],
    'prePR': [
      {d: 'dark_risotto.html', p: 'Risotto', f: 'La Santa'},
    ],
    'prePV': [
      {d: 'dark_verduras.html', p: 'Arroz Verduras', f: 'La Santa'},
    ],
    'preSalm': [
      {d: 'dark_pollo.html', p: 'Arroz Pollo', f: 'La Santa'},
      {d: 'dark_verduras.html', p: 'Arroz Verduras', f: 'La Santa'},
    ],
    'prepM': [
      {d: 'dark_maestro.html', p: 'Maestro', f: 'Maestro'},
    ],
    'prod': [
      {d: 'dark_cremoso_iberico.html', p: 'Cremoso Ibérico', f: 'All-Included'},
      {d: 'dark_cremoso_queso.html', p: 'Cremoso Queso', f: 'All-Included'},
      {d: 'dark_cremoso_setas.html', p: 'Cremoso Setas', f: 'All-Included'},
      {d: 'dark_cremoso_tartufato.html', p: 'Cremoso Tartufato', f: 'All-Included'},
      {d: 'dark_maestro.html', p: 'Maestro', f: 'Maestro'},
      {d: 'dark_negro.html', p: 'Arroz Negro', f: 'La Santa'},
      {d: 'dark_pescado.html', p: 'Arroz Pescado', f: 'La Santa'},
      {d: 'dark_pollo.html', p: 'Arroz Pollo', f: 'La Santa'},
      {d: 'dark_risotto.html', p: 'Risotto', f: 'La Santa'},
      {d: 'dark_verduras.html', p: 'Arroz Verduras', f: 'La Santa'},
    ],
    'prodRis': [
      {d: 'dark_salsa_boletus.html', p: 'Salsa Boletus', f: 'Salsas'},
      {d: 'dark_salsa_iberica.html', p: 'Salsa Ibérico', f: 'Salsas'},
      {d: 'dark_salsa_negra.html', p: 'Salsa Negra', f: 'Salsas'},
      {d: 'dark_salsa_pescado.html', p: 'Salsa Pescado', f: 'Salsas'},
      {d: 'dark_salsa_pollo.html', p: 'Salsa Pollo', f: 'Salsas'},
      {d: 'dark_salsa_queso.html', p: 'Salsa Queso', f: 'Salsas'},
      {d: 'dark_salsa_tartufata.html', p: 'Salsa Tartufata', f: 'Salsas'},
      {d: 'dark_salsa_verduras.html', p: 'Salsa Verduras', f: 'Salsas'},
    ],
    'salIb': [
      {d: 'dark_cremoso_iberico.html', p: 'Cremoso Ibérico', f: 'All-Included'},
    ],
    'salQue': [
      {d: 'dark_cremoso_queso.html', p: 'Cremoso Queso', f: 'All-Included'},
    ],
    'salSet': [
      {d: 'dark_cremoso_setas.html', p: 'Cremoso Setas', f: 'All-Included'},
    ],
    'salTar': [
      {d: 'dark_cremoso_tartufato.html', p: 'Cremoso Tartufato', f: 'All-Included'},
    ],
    'salsa': [
      {d: 'dark_salsa_boletus.html', p: 'Salsa Boletus', f: 'Salsas'},
      {d: 'dark_salsa_iberica.html', p: 'Salsa Ibérico', f: 'Salsas'},
      {d: 'dark_salsa_negra.html', p: 'Salsa Negra', f: 'Salsas'},
      {d: 'dark_salsa_pescado.html', p: 'Salsa Pescado', f: 'Salsas'},
      {d: 'dark_salsa_pollo.html', p: 'Salsa Pollo', f: 'Salsas'},
      {d: 'dark_salsa_queso.html', p: 'Salsa Queso', f: 'Salsas'},
      {d: 'dark_salsa_tartufata.html', p: 'Salsa Tartufata', f: 'Salsas'},
      {d: 'dark_salsa_verduras.html', p: 'Salsa Verduras', f: 'Salsas'},
    ],
  },

  // MP codes to ficha técnica data with PDF file URLs
  fichasTecnicas: {
    'mp01': {nombre: 'Caldo Aneto Pescado', proveedor: 'Aneto', url: 'https://drive.google.com/drive/folders/1BVsoRhvrB2xVRw8oYy3c9JpECBomHx-Y'},
    'mp03': {nombre: 'Paeller Pollo', proveedor: 'Caldos Paeller', url: 'https://drive.google.com/drive/folders/14_x5-3o3-J60TGEDsdF06wc7s06x797K'},
    'mp04': {nombre: 'Aceite girasol alto oleico', proveedor: 'Coreysa', url: 'https://drive.google.com/file/d/1qGTVaT42QRvtiy7hLia10yrri_2VIJn2/view'},
    'mp05': {nombre: 'Aceite oliva virgen', proveedor: 'Makro', url: 'https://drive.google.com/drive/folders/1MAAqJjeW3rWXdIMt8tjzlpMORppLZbMO'},
    'mp06': {nombre: 'Umami', proveedor: 'Givaudan', url: 'https://drive.google.com/drive/folders/1HGKb1KAwa8EdQind601XHifbxwpopFnq'},
    'mp07': {nombre: 'Xantana', proveedor: 'Corquimia/Xantana', url: 'https://drive.google.com/drive/folders/1s9knhOB4VdRdygbT7NmsiDlY7rSxS7Dp'},
    'mp08': {nombre: 'Tinta de calamar', proveedor: 'Nortindal', url: 'https://drive.google.com/drive/folders/1xoggA9ZKcb-jHNwAdoXwDumm4bsiFUHX'},
    'mp09': {nombre: 'Hazelnut (colorante)', proveedor: 'Sensient', url: 'https://drive.google.com/drive/folders/1gH58oWgfF30HguhBabwFPU3aYdPQS2KF'},
    'mp10': {nombre: 'Pimentón', proveedor: 'Coato', url: 'https://drive.google.com/drive/folders/15fObM80xHzaYjncbQBq_TLkCAEgg80My'},
    'mp11': {nombre: 'Hierbas (mezcla)', proveedor: 'Expressions Aromatiques', url: 'https://drive.google.com/drive/folders/1IT3K-bek2mM8iRcgfphHc6-wWyH00ewh'},
    'mp12': {nombre: 'Almidón', proveedor: 'Ingredion', url: 'https://drive.google.com/drive/folders/1W4DRpTJzUE4WF7gKSv9ER1IsRpOpTNWG'},
    'mp13': {nombre: 'Mantequilla', proveedor: 'Presidente/Mantequilla', url: 'https://drive.google.com/drive/folders/1wMeDsLZtb9GDiFreBoYGXDkTkWaB1SbQ'},
    'mp19': {nombre: 'Azafrán', proveedor: 'Verdú Cantó', url: 'https://drive.google.com/drive/folders/1Fjkdysu9PyUo8el9pdcDWsJDhPaKrmFC'},
    'mp20': {nombre: 'Jamón Ibérico', proveedor: 'Enrique Tomás', url: 'https://drive.google.com/drive/folders/1VXZ5E4jgj4B6OyN6mHkMoZweataGnI-j'},
    'mp21': {nombre: 'Harina Fina de Boletus', proveedor: 'Honza', url: 'https://drive.google.com/drive/folders/1Pq3Th7-CvFRZqs6Ys-Vs3vDxzJtAoHwI'},
    'mp22': {nombre: 'Mezcla Setas con Boletus', proveedor: 'Honza', url: 'https://drive.google.com/drive/folders/1Pq3Th7-CvFRZqs6Ys-Vs3vDxzJtAoHwI'},
    'mp23': {nombre: 'Tartufata pasta trufa', proveedor: 'Solchem', url: 'https://drive.google.com/drive/folders/1ILIbFB6shtYxY02QKBR4Dsd69rASSBQ0'},
    'mp24': {nombre: 'Arroz Nuovo Maratelli', proveedor: 'Arrocera Pirineo', url: 'https://drive.google.com/file/d/1bd30UpqSM2p8OhSz3h1ByEZ4j_uvvNz_/view'},
    'mp31': {nombre: 'Ñora en lata', proveedor: 'Rajope', url: 'https://drive.google.com/drive/folders/14Y5TrAfb7BcJCH82AS6mG4rKlL3Vay8s'},
    'mp33': {nombre: 'Espinaca deshidratada', proveedor: 'La Margarita', url: 'https://drive.google.com/drive/folders/1QaFyByoRzB4pB8asHAlrk6w9aFZJ2A-q'},
    'mp34': {nombre: 'Cebolla deshidratada', proveedor: 'Dalmau', url: 'https://drive.google.com/drive/folders/123tPERK4BqmmOFwmLbDyvgTBEa0K5M5v'},
    'mp35': {nombre: 'Pollo deshidratado', proveedor: 'Ugeave', url: 'https://drive.google.com/drive/folders/1AxRLbDkx66WHYQnzU34ivpTsCI9NIXCP'},
    'mp36': {nombre: 'Puerro deshidratado', proveedor: 'Dalmau', url: 'https://drive.google.com/drive/folders/123tPERK4BqmmOFwmLbDyvgTBEa0K5M5v'},
    'mp37': {nombre: 'Sal', proveedor: 'Sal', url: 'https://drive.google.com/drive/folders/1zUCFdwS4WkNvzhGsjBpjFnwdefTCyVeo'},
    'mp38': {nombre: 'Ácido tartárico', proveedor: 'SEAH', url: 'https://drive.google.com/drive/folders/1esl-m65taI-t_2NK4G6vgcfdISOZIfE2'},
    'mp39': {nombre: 'Azúcar', proveedor: 'Azucarera', url: 'https://drive.google.com/drive/folders/1gKcRdutldZlsnBVKdZ-Xbe3SCNUm8I1b'},
    'mp40': {nombre: 'Ajo', proveedor: 'Ajopel', url: 'https://drive.google.com/file/d/1Ojt6683opzmVAHe1PGzC-O2Ppza3CqrF/view'},
    'mp50': {nombre: 'Bandeja EOS-35', proveedor: 'Sarabia', url: 'https://drive.google.com/file/d/1MNeJj9DrWjMgPUv-2w-R7-9mVfcG4sdc/view'},
    'mp51': {nombre: 'Film top-seal', proveedor: 'Adrados', url: 'https://drive.google.com/file/d/1Sd4LLvPNtS3qwsZmy3ElErreIm1UduEe/view'},
    'mp52': {nombre: 'Etiqueta producto', proveedor: '(sin asignar)', url: ''},
    'mp65': {nombre: 'Vino (Manzanilla/Jerez)', proveedor: 'Barbadillo', url: ''},
    'mp66': {nombre: 'Grasa de pollo', proveedor: 'Ugeave', url: 'https://drive.google.com/drive/folders/1AxRLbDkx66WHYQnzU34ivpTsCI9NIXCP'},
    'mp73': {nombre: 'Queso azul', proveedor: 'Queso', url: 'https://drive.google.com/drive/folders/1kAaJnflNAL66nUzOcxYCig6vM3PEloEc'},
    'mpAceite': {nombre: 'Aceite girasol alto oleico', proveedor: 'Coreysa', url: 'https://drive.google.com/file/d/1qGTVaT42QRvtiy7hLia10yrri_2VIJn2/view'},
    'mpAceiteTrufado': {nombre: 'Aceite trufado', proveedor: 'Solchem', url: 'https://drive.google.com/drive/folders/1ILIbFB6shtYxY02QKBR4Dsd69rASSBQ0'},
    'mpAg': {nombre: 'Agua', proveedor: 'Water', url: ''},
    'mpAgua': {nombre: 'Agua', proveedor: 'Water', url: ''},
    'mpAgua1': {nombre: 'Agua', proveedor: 'Water', url: ''},
    'mpAguaAlmidonada': {nombre: 'Agua almidonada', proveedor: 'Water', url: ''},
    'mpAjo': {nombre: 'Ajo', proveedor: 'Ajopel', url: 'https://drive.google.com/file/d/1Ojt6683opzmVAHe1PGzC-O2Ppza3CqrF/view'},
    'mpArr': {nombre: 'Arroz', proveedor: 'Arrocera Pirineo', url: 'https://drive.google.com/file/d/1bd30UpqSM2p8OhSz3h1ByEZ4j_uvvNz_/view'},
    'mpAromaJamon': {nombre: 'Aroma de jamón', proveedor: 'Givaudan', url: 'https://drive.google.com/drive/folders/1HGKb1KAwa8EdQind601XHifbxwpopFnq'},
    'mpAromaQue': {nombre: 'Aroma de queso', proveedor: 'Givaudan', url: 'https://drive.google.com/drive/folders/1HGKb1KAwa8EdQind601XHifbxwpopFnq'},
    'mpAromaQueso': {nombre: 'Aroma de queso', proveedor: 'Givaudan', url: 'https://drive.google.com/drive/folders/1HGKb1KAwa8EdQind601XHifbxwpopFnq'},
    'mpBand': {nombre: 'Bandeja', proveedor: 'Sarabia', url: 'https://drive.google.com/file/d/1MNeJj9DrWjMgPUv-2w-R7-9mVfcG4sdc/view'},
    'mpCMC': {nombre: 'CMC (carboximetilcelulosa)', proveedor: 'Dalmau', url: ''},
    'mpCaldoPescado': {nombre: 'Caldo Pescado prelab.', proveedor: 'Aneto', url: 'https://drive.google.com/drive/folders/1BVsoRhvrB2xVRw8oYy3c9JpECBomHx-Y'},
    'mpCaldoPollo': {nombre: 'Caldo Pollo prelab.', proveedor: 'Caldos Paeller', url: 'https://drive.google.com/drive/folders/14_x5-3o3-J60TGEDsdF06wc7s06x797K'},
    'mpCeb': {nombre: 'Cebolla deshidratada', proveedor: 'Dalmau', url: 'https://drive.google.com/drive/folders/123tPERK4BqmmOFwmLbDyvgTBEa0K5M5v'},
    'mpCur': {nombre: 'Cúrcuma', proveedor: 'Ajopel', url: 'https://drive.google.com/file/d/1Ojt6683opzmVAHe1PGzC-O2Ppza3CqrF/view'},
    'mpFilm': {nombre: 'Film', proveedor: 'Adrados', url: 'https://drive.google.com/file/d/1Sd4LLvPNtS3qwsZmy3ElErreIm1UduEe/view'},
    'mpGraPollo': {nombre: 'Grasa de pollo', proveedor: 'Ugeave', url: 'https://drive.google.com/drive/folders/1AxRLbDkx66WHYQnzU34ivpTsCI9NIXCP'},
    'mpGrasaPollo': {nombre: 'Grasa de pollo', proveedor: 'Ugeave', url: 'https://drive.google.com/drive/folders/1AxRLbDkx66WHYQnzU34ivpTsCI9NIXCP'},
    'mpHazelnut': {nombre: 'Hazelnut (colorante)', proveedor: 'Sensient', url: 'https://drive.google.com/drive/folders/1gH58oWgfF30HguhBabwFPU3aYdPQS2KF'},
    'mpJamon': {nombre: 'Jamón', proveedor: 'Enrique Tomás', url: 'https://drive.google.com/drive/folders/1VXZ5E4jgj4B6OyN6mHkMoZweataGnI-j'},
    'mpJerez': {nombre: 'Vinagre de Jerez', proveedor: 'Makro', url: 'https://drive.google.com/drive/folders/1MAAqJjeW3rWXdIMt8tjzlpMORppLZbMO'},
    'mpMant': {nombre: 'Mantequilla', proveedor: 'Presidente/Mantequilla', url: 'https://drive.google.com/drive/folders/1wMeDsLZtb9GDiFreBoYGXDkTkWaB1SbQ'},
    'mpManzanilla': {nombre: 'Vino manzanilla', proveedor: 'Makro', url: 'https://drive.google.com/drive/folders/1MAAqJjeW3rWXdIMt8tjzlpMORppLZbMO'},
    'mpNata': {nombre: 'Nata', proveedor: 'Mantequilla/Presidente', url: 'https://drive.google.com/drive/folders/1wMeDsLZtb9GDiFreBoYGXDkTkWaB1SbQ'},
    'mpParm': {nombre: 'Parmesano rallado', proveedor: 'Queso', url: 'https://drive.google.com/drive/folders/1kAaJnflNAL66nUzOcxYCig6vM3PEloEc'},
    'mpPimienta': {nombre: 'Pimienta', proveedor: 'Makro', url: 'https://drive.google.com/drive/folders/1MAAqJjeW3rWXdIMt8tjzlpMORppLZbMO'},
    'mpQuesoAzul': {nombre: 'Queso azul', proveedor: 'Queso', url: 'https://drive.google.com/drive/folders/1kAaJnflNAL66nUzOcxYCig6vM3PEloEc'},
    'mpSal': {nombre: 'Sal', proveedor: 'Sal', url: 'https://drive.google.com/drive/folders/1zUCFdwS4WkNvzhGsjBpjFnwdefTCyVeo'},
    'mpSalmorreta': {nombre: 'Salmorreta prelab.', proveedor: 'Preelaboración', url: ''},
    'mpSalsaVerd': {nombre: 'Salsa Verduras prelab.', proveedor: 'Preelaboración', url: ''},
    'mpTinta': {nombre: 'Tinta de calamar', proveedor: 'Nortindal', url: 'https://drive.google.com/drive/folders/1xoggA9ZKcb-jHNwAdoXwDumm4bsiFUHX'},
    'mpUmami': {nombre: 'Umami', proveedor: 'Givaudan', url: 'https://drive.google.com/drive/folders/1HGKb1KAwa8EdQind601XHifbxwpopFnq'},
    'mpVino': {nombre: 'Vino blanco', proveedor: 'Makro', url: 'https://drive.google.com/drive/folders/1MAAqJjeW3rWXdIMt8tjzlpMORppLZbMO'},
    'mpXantana': {nombre: 'Xantana', proveedor: 'Corquimia/Xantana', url: 'https://drive.google.com/drive/folders/1s9knhOB4VdRdygbT7NmsiDlY7rSxS7Dp'},
  },

  // Diagram metadata
  diagramas: {
    'dark_pescado.html': {nombre: 'Arroz Pescado y Marisco', familia: 'La Santa'},
    'dark_negro.html': {nombre: 'Arroz Negro', familia: 'La Santa'},
    'dark_pollo.html': {nombre: 'Arroz Pollo', familia: 'La Santa'},
    'dark_verduras.html': {nombre: 'Arroz Verduras', familia: 'La Santa'},
    'dark_risotto.html': {nombre: 'Risotto', familia: 'La Santa'},
    'dark_cremoso_iberico.html': {nombre: 'Cremoso Ibérico', familia: 'All-Included'},
    'dark_cremoso_queso.html': {nombre: 'Cremoso Queso', familia: 'All-Included'},
    'dark_cremoso_setas.html': {nombre: 'Cremoso Setas', familia: 'All-Included'},
    'dark_cremoso_tartufato.html': {nombre: 'Cremoso Tartufato', familia: 'All-Included'},
    'dark_salsa_boletus.html': {nombre: 'Salsa Boletus', familia: 'Salsas'},
    'dark_salsa_iberica.html': {nombre: 'Salsa Ibérico', familia: 'Salsas'},
    'dark_salsa_negra.html': {nombre: 'Salsa Negra', familia: 'Salsas'},
    'dark_salsa_pescado.html': {nombre: 'Salsa Pescado', familia: 'Salsas'},
    'dark_salsa_pollo.html': {nombre: 'Salsa Pollo', familia: 'Salsas'},
    'dark_salsa_queso.html': {nombre: 'Salsa Queso', familia: 'Salsas'},
    'dark_salsa_tartufata.html': {nombre: 'Salsa Tartufata', familia: 'Salsas'},
    'dark_salsa_verduras.html': {nombre: 'Salsa Verduras', familia: 'Salsas'},
    'dark_maestro.html': {nombre: 'Maestro', familia: 'Maestro'},
  }
};
