// Cross-reference data for production flow diagram traceability
// Maps node IDs to diagrams, metadata, and ficha técnica URLs

const CROSS_REF = {
  // Node ID → [{d: diagram filename, p: product name, f: family}]
  presenteEn: {
    // bolsa, cajaRis: excluidos (nodos de empaquetado, no necesitan "Presente en")
    'calN': [
      {d: 'dark_negro.html', p: 'Arroz Negro', f: 'La Santa'},
    ],
    'calP': [
      {d: 'dark_pescado.html', p: 'Arroz Pescado', f: 'La Santa'},
    ],
    'calPo': [
      {d: 'dark_pollo.html', p: 'Arroz Pollo', f: 'La Santa'},
    ],
    'calR': [
      {d: 'dark_cremoso_iberico.html', p: 'Cremoso Ibérico', f: 'Cremosos'},
      {d: 'dark_cremoso_queso.html', p: 'Cremoso Queso', f: 'Cremosos'},
      {d: 'dark_cremoso_setas.html', p: 'Cremoso Setas', f: 'Cremosos'},
      {d: 'dark_cremoso_tartufato.html', p: 'Cremoso Tartufato', f: 'Cremosos'},
      {d: 'dark_risotto.html', p: 'Risotto', f: 'La Santa'},
    ],
    'calV': [
      {d: 'dark_verduras.html', p: 'Arroz Verduras', f: 'La Santa'},
    ],
    'jarP': [
      {d: 'dark_negro.html', p: 'Arroz Negro', f: 'La Santa'},
      {d: 'dark_pescado.html', p: 'Arroz Pescado', f: 'La Santa'},
      {d: 'dark_pollo.html', p: 'Arroz Pollo', f: 'La Santa'},
    ],
    'jarR': [
      {d: 'dark_cremoso_iberico.html', p: 'Cremoso Ibérico', f: 'Cremosos'},
      {d: 'dark_cremoso_queso.html', p: 'Cremoso Queso', f: 'Cremosos'},
      {d: 'dark_cremoso_setas.html', p: 'Cremoso Setas', f: 'Cremosos'},
      {d: 'dark_cremoso_tartufato.html', p: 'Cremoso Tartufato', f: 'Cremosos'},
      {d: 'dark_risotto.html', p: 'Risotto', f: 'La Santa'},
    ],
    'jarV': [
      {d: 'dark_verduras.html', p: 'Arroz Verduras', f: 'La Santa'},
    ],
    'mezJ': [
      {d: 'dark_negro.html', p: 'Arroz Negro', f: 'La Santa'},
      {d: 'dark_pescado.html', p: 'Arroz Pescado', f: 'La Santa'},
      {d: 'dark_pollo.html', p: 'Arroz Pollo', f: 'La Santa'},
      {d: 'dark_verduras.html', p: 'Arroz Verduras', f: 'La Santa'},
    ],
    'mezJM': [
      {d: 'dark_maestro.html', p: 'Maestro', f: 'Maestro'},
    ],
    'mezJR': [
      {d: 'dark_cremoso_iberico.html', p: 'Cremoso Ibérico', f: 'Cremosos'},
      {d: 'dark_cremoso_queso.html', p: 'Cremoso Queso', f: 'Cremosos'},
      {d: 'dark_cremoso_setas.html', p: 'Cremoso Setas', f: 'Cremosos'},
      {d: 'dark_cremoso_tartufato.html', p: 'Cremoso Tartufato', f: 'Cremosos'},
    ],
    'mezR': [
      {d: 'dark_risotto.html', p: 'Risotto', f: 'La Santa'},
    ],
    'mp01': [
      {d: 'dark_negro.html', p: 'Arroz Negro', f: 'La Santa'},
      {d: 'dark_pescado.html', p: 'Arroz Pescado', f: 'La Santa'},
    ],
    'mp03': [
      {d: 'dark_pollo.html', p: 'Arroz Pollo', f: 'La Santa'},
    ],
    'mp04': [
      {d: 'dark_cremoso_iberico.html', p: 'Cremoso Ibérico', f: 'Cremosos'},
      {d: 'dark_cremoso_queso.html', p: 'Cremoso Queso', f: 'Cremosos'},
      {d: 'dark_cremoso_setas.html', p: 'Cremoso Setas', f: 'Cremosos'},
      {d: 'dark_cremoso_tartufato.html', p: 'Cremoso Tartufato', f: 'Cremosos'},
      {d: 'dark_negro.html', p: 'Arroz Negro', f: 'La Santa'},
      {d: 'dark_pescado.html', p: 'Arroz Pescado', f: 'La Santa'},
      {d: 'dark_pollo.html', p: 'Arroz Pollo', f: 'La Santa'},
      {d: 'dark_risotto.html', p: 'Risotto', f: 'La Santa'},
      {d: 'dark_salsa_boletus.html', p: 'Salsa Boletus', f: 'Salsas'},
      {d: 'dark_verduras.html', p: 'Arroz Verduras', f: 'La Santa'},
    ],
    'mp05': [
      {d: 'dark_pollo.html', p: 'Arroz Pollo', f: 'La Santa'},
      {d: 'dark_verduras.html', p: 'Arroz Verduras', f: 'La Santa'},
    ],
    'mp06': [
      {d: 'dark_cremoso_iberico.html', p: 'Cremoso Ibérico', f: 'Cremosos'},
      {d: 'dark_cremoso_queso.html', p: 'Cremoso Queso', f: 'Cremosos'},
      {d: 'dark_cremoso_setas.html', p: 'Cremoso Setas', f: 'Cremosos'},
      {d: 'dark_cremoso_tartufato.html', p: 'Cremoso Tartufato', f: 'Cremosos'},
      {d: 'dark_maestro.html', p: 'Maestro', f: 'Maestro'},
      {d: 'dark_negro.html', p: 'Arroz Negro', f: 'La Santa'},
      {d: 'dark_pescado.html', p: 'Arroz Pescado', f: 'La Santa'},
      {d: 'dark_pollo.html', p: 'Arroz Pollo', f: 'La Santa'},
      {d: 'dark_risotto.html', p: 'Risotto', f: 'La Santa'},
      {d: 'dark_salsa_boletus.html', p: 'Salsa Boletus', f: 'Salsas'},
      {d: 'dark_verduras.html', p: 'Arroz Verduras', f: 'La Santa'},
    ],
    'mp07': [
      {d: 'dark_cremoso_iberico.html', p: 'Cremoso Ibérico', f: 'Cremosos'},
      {d: 'dark_cremoso_queso.html', p: 'Cremoso Queso', f: 'Cremosos'},
      {d: 'dark_cremoso_setas.html', p: 'Cremoso Setas', f: 'Cremosos'},
      {d: 'dark_cremoso_tartufato.html', p: 'Cremoso Tartufato', f: 'Cremosos'},
      {d: 'dark_negro.html', p: 'Arroz Negro', f: 'La Santa'},
      {d: 'dark_pescado.html', p: 'Arroz Pescado', f: 'La Santa'},
      {d: 'dark_pollo.html', p: 'Arroz Pollo', f: 'La Santa'},
      {d: 'dark_risotto.html', p: 'Risotto', f: 'La Santa'},
      {d: 'dark_salsa_boletus.html', p: 'Salsa Boletus', f: 'Salsas'},
      {d: 'dark_verduras.html', p: 'Arroz Verduras', f: 'La Santa'},
    ],
    'mp08': [
      {d: 'dark_negro.html', p: 'Arroz Negro', f: 'La Santa'},
    ],
    'mp09': [
      {d: 'dark_cremoso_iberico.html', p: 'Cremoso Ibérico', f: 'Cremosos'},
      {d: 'dark_cremoso_queso.html', p: 'Cremoso Queso', f: 'Cremosos'},
      {d: 'dark_cremoso_setas.html', p: 'Cremoso Setas', f: 'Cremosos'},
      {d: 'dark_cremoso_tartufato.html', p: 'Cremoso Tartufato', f: 'Cremosos'},
      {d: 'dark_maestro.html', p: 'Maestro', f: 'Maestro'},
      {d: 'dark_negro.html', p: 'Arroz Negro', f: 'La Santa'},
      {d: 'dark_pescado.html', p: 'Arroz Pescado', f: 'La Santa'},
      {d: 'dark_pollo.html', p: 'Arroz Pollo', f: 'La Santa'},
      {d: 'dark_risotto.html', p: 'Risotto', f: 'La Santa'},
      {d: 'dark_salsa_boletus.html', p: 'Salsa Boletus', f: 'Salsas'},
      {d: 'dark_verduras.html', p: 'Arroz Verduras', f: 'La Santa'},
    ],
    'mp10': [
      {d: 'dark_pescado.html', p: 'Arroz Pescado', f: 'La Santa'},
      {d: 'dark_verduras.html', p: 'Arroz Verduras', f: 'La Santa'},
    ],
    'mp11': [
      {d: 'dark_verduras.html', p: 'Arroz Verduras', f: 'La Santa'},
    ],
    'mp12': [
      {d: 'dark_risotto.html', p: 'Risotto', f: 'La Santa'},
    ],
    'mp13': [
      {d: 'dark_cremoso_iberico.html', p: 'Cremoso Ibérico', f: 'Cremosos'},
      {d: 'dark_cremoso_queso.html', p: 'Cremoso Queso', f: 'Cremosos'},
      {d: 'dark_cremoso_setas.html', p: 'Cremoso Setas', f: 'Cremosos'},
      {d: 'dark_cremoso_tartufato.html', p: 'Cremoso Tartufato', f: 'Cremosos'},
      {d: 'dark_risotto.html', p: 'Risotto', f: 'La Santa'},
    ],
    'mp19': [
      {d: 'dark_maestro.html', p: 'Maestro', f: 'Maestro'},
      {d: 'dark_pescado.html', p: 'Arroz Pescado', f: 'La Santa'},
      {d: 'dark_pollo.html', p: 'Arroz Pollo', f: 'La Santa'},
      {d: 'dark_verduras.html', p: 'Arroz Verduras', f: 'La Santa'},
    ],
    'mp21': [
      {d: 'dark_salsa_boletus.html', p: 'Salsa Boletus', f: 'Salsas'},
    ],
    'mp22': [
      {d: 'dark_cremoso_setas.html', p: 'Cremoso Setas', f: 'Cremosos'},
    ],
    'mp23': [
      {d: 'dark_cremoso_tartufato.html', p: 'Cremoso Tartufato', f: 'Cremosos'},
    ],
    'mp31': [
      {d: 'dark_pescado.html', p: 'Arroz Pescado', f: 'La Santa'},
      {d: 'dark_pollo.html', p: 'Arroz Pollo', f: 'La Santa'},
      {d: 'dark_verduras.html', p: 'Arroz Verduras', f: 'La Santa'},
    ],
    'mp33': [
      {d: 'dark_negro.html', p: 'Arroz Negro', f: 'La Santa'},
      {d: 'dark_pescado.html', p: 'Arroz Pescado', f: 'La Santa'},
      {d: 'dark_pollo.html', p: 'Arroz Pollo', f: 'La Santa'},
      {d: 'dark_verduras.html', p: 'Arroz Verduras', f: 'La Santa'},
    ],
    'mp34': [
      {d: 'dark_risotto.html', p: 'Risotto', f: 'La Santa'},
      {d: 'dark_verduras.html', p: 'Arroz Verduras', f: 'La Santa'},
    ],
    'mp35': [
      {d: 'dark_cremoso_iberico.html', p: 'Cremoso Ibérico', f: 'Cremosos'},
      {d: 'dark_cremoso_queso.html', p: 'Cremoso Queso', f: 'Cremosos'},
      {d: 'dark_cremoso_setas.html', p: 'Cremoso Setas', f: 'Cremosos'},
      {d: 'dark_cremoso_tartufato.html', p: 'Cremoso Tartufato', f: 'Cremosos'},
      {d: 'dark_negro.html', p: 'Arroz Negro', f: 'La Santa'},
      {d: 'dark_pescado.html', p: 'Arroz Pescado', f: 'La Santa'},
      {d: 'dark_pollo.html', p: 'Arroz Pollo', f: 'La Santa'},
      {d: 'dark_risotto.html', p: 'Risotto', f: 'La Santa'},
    ],
    'mp36': [
      {d: 'dark_risotto.html', p: 'Risotto', f: 'La Santa'},
      {d: 'dark_verduras.html', p: 'Arroz Verduras', f: 'La Santa'},
    ],
    'mp38': [
      {d: 'dark_maestro.html', p: 'Maestro', f: 'Maestro'},
      {d: 'dark_risotto.html', p: 'Risotto', f: 'La Santa'},
    ],
    'mp39': [
      {d: 'dark_risotto.html', p: 'Risotto', f: 'La Santa'},
    ],
    'mp42': [
      {d: 'dark_pollo.html', p: 'Arroz Pollo', f: 'La Santa'},
      {d: 'dark_verduras.html', p: 'Arroz Verduras', f: 'La Santa'},
    ],
    'mp52': [
      {d: 'dark_maestro.html', p: 'Maestro', f: 'Maestro'},
    ],
    'mp53': [
      {d: 'dark_maestro.html', p: 'Maestro', f: 'Maestro'},
    ],
    'mp65': [
      {d: 'dark_salsa_boletus.html', p: 'Salsa Boletus', f: 'Salsas'},
    ],
    'mp66': [
      {d: 'dark_salsa_boletus.html', p: 'Salsa Boletus', f: 'Salsas'},
    ],
    'mp73': [
      {d: 'dark_cremoso_queso.html', p: 'Cremoso Queso', f: 'Cremosos'},
    ],
    'mpAceite': [
      {d: 'dark_salsa_iberica.html', p: 'Salsa Ibérico', f: 'Salsas'},
      {d: 'dark_salsa_queso.html', p: 'Salsa Queso', f: 'Salsas'},
      {d: 'dark_salsa_tartufata.html', p: 'Salsa Tartufata', f: 'Salsas'},
    ],
    'mpAceiteTrufado': [
      {d: 'dark_salsa_tartufata.html', p: 'Salsa Tartufata', f: 'Salsas'},
    ],
    'mpAg': [
      {d: 'dark_cremoso_iberico.html', p: 'Cremoso Ibérico', f: 'Cremosos'},
      {d: 'dark_cremoso_queso.html', p: 'Cremoso Queso', f: 'Cremosos'},
      {d: 'dark_cremoso_setas.html', p: 'Cremoso Setas', f: 'Cremosos'},
      {d: 'dark_cremoso_tartufato.html', p: 'Cremoso Tartufato', f: 'Cremosos'},
      {d: 'dark_maestro.html', p: 'Maestro', f: 'Maestro'},
      {d: 'dark_negro.html', p: 'Arroz Negro', f: 'La Santa'},
      {d: 'dark_pescado.html', p: 'Arroz Pescado', f: 'La Santa'},
      {d: 'dark_pollo.html', p: 'Arroz Pollo', f: 'La Santa'},
      {d: 'dark_risotto.html', p: 'Risotto', f: 'La Santa'},
      {d: 'dark_salsa_boletus.html', p: 'Salsa Boletus', f: 'Salsas'},
      {d: 'dark_verduras.html', p: 'Arroz Verduras', f: 'La Santa'},
    ],
    'mpAgua': [
      {d: 'dark_salsa_iberica.html', p: 'Salsa Ibérico', f: 'Salsas'},
      {d: 'dark_salsa_pescado.html', p: 'Salsa Pescado', f: 'Salsas'},
      {d: 'dark_salsa_pollo.html', p: 'Salsa Pollo', f: 'Salsas'},
      {d: 'dark_salsa_queso.html', p: 'Salsa Queso', f: 'Salsas'},
      {d: 'dark_salsa_tartufata.html', p: 'Salsa Tartufata', f: 'Salsas'},
    ],
    'mpAgua1': [
      {d: 'dark_salsa_verduras.html', p: 'Salsa Verduras', f: 'Salsas'},
    ],
    'mpAguaAlmidonada': [
      {d: 'dark_salsa_verduras.html', p: 'Salsa Verduras', f: 'Salsas'},
    ],
    'mpAjo': [
      {d: 'dark_cremoso_iberico.html', p: 'Cremoso Ibérico', f: 'Cremosos'},
      {d: 'dark_cremoso_queso.html', p: 'Cremoso Queso', f: 'Cremosos'},
      {d: 'dark_cremoso_setas.html', p: 'Cremoso Setas', f: 'Cremosos'},
      {d: 'dark_cremoso_tartufato.html', p: 'Cremoso Tartufato', f: 'Cremosos'},
      {d: 'dark_negro.html', p: 'Arroz Negro', f: 'La Santa'},
      {d: 'dark_pescado.html', p: 'Arroz Pescado', f: 'La Santa'},
      {d: 'dark_pollo.html', p: 'Arroz Pollo', f: 'La Santa'},
      {d: 'dark_risotto.html', p: 'Risotto', f: 'La Santa'},
      {d: 'dark_verduras.html', p: 'Arroz Verduras', f: 'La Santa'},
    ],
    'mpAromaJamon': [
      {d: 'dark_salsa_iberica.html', p: 'Salsa Ibérico', f: 'Salsas'},
    ],
    'mpAromaQ': [
      {d: 'dark_salsa_boletus.html', p: 'Salsa Boletus', f: 'Salsas'},
    ],
    'mpAromaQue': [
      {d: 'dark_cremoso_queso.html', p: 'Cremoso Queso', f: 'Cremosos'},
    ],
    'mpAromaQueso': [
      {d: 'dark_salsa_queso.html', p: 'Salsa Queso', f: 'Salsas'},
    ],
    'mpArr': [
      {d: 'dark_cremoso_iberico.html', p: 'Cremoso Ibérico', f: 'Cremosos'},
      {d: 'dark_cremoso_queso.html', p: 'Cremoso Queso', f: 'Cremosos'},
      {d: 'dark_cremoso_setas.html', p: 'Cremoso Setas', f: 'Cremosos'},
      {d: 'dark_cremoso_tartufato.html', p: 'Cremoso Tartufato', f: 'Cremosos'},
      {d: 'dark_maestro.html', p: 'Maestro', f: 'Maestro'},
      {d: 'dark_negro.html', p: 'Arroz Negro', f: 'La Santa'},
      {d: 'dark_pescado.html', p: 'Arroz Pescado', f: 'La Santa'},
      {d: 'dark_pollo.html', p: 'Arroz Pollo', f: 'La Santa'},
      {d: 'dark_risotto.html', p: 'Risotto', f: 'La Santa'},
      {d: 'dark_verduras.html', p: 'Arroz Verduras', f: 'La Santa'},
    ],
    'mpBand': [
      {d: 'dark_cremoso_iberico.html', p: 'Cremoso Ibérico', f: 'Cremosos'},
      {d: 'dark_cremoso_queso.html', p: 'Cremoso Queso', f: 'Cremosos'},
      {d: 'dark_cremoso_setas.html', p: 'Cremoso Setas', f: 'Cremosos'},
      {d: 'dark_cremoso_tartufato.html', p: 'Cremoso Tartufato', f: 'Cremosos'},
      {d: 'dark_maestro.html', p: 'Maestro', f: 'Maestro'},
      {d: 'dark_negro.html', p: 'Arroz Negro', f: 'La Santa'},
      {d: 'dark_pescado.html', p: 'Arroz Pescado', f: 'La Santa'},
      {d: 'dark_pollo.html', p: 'Arroz Pollo', f: 'La Santa'},
      {d: 'dark_risotto.html', p: 'Risotto', f: 'La Santa'},
      {d: 'dark_verduras.html', p: 'Arroz Verduras', f: 'La Santa'},
    ],
    'mpCMC': [
      {d: 'dark_salsa_iberica.html', p: 'Salsa Ibérico', f: 'Salsas'},
      {d: 'dark_salsa_queso.html', p: 'Salsa Queso', f: 'Salsas'},
    ],
    'mpCaldoPescado': [
      {d: 'dark_salsa_negra.html', p: 'Salsa Negra', f: 'Salsas'},
      {d: 'dark_salsa_pescado.html', p: 'Salsa Pescado', f: 'Salsas'},
    ],
    'mpCaldoPollo': [
      {d: 'dark_salsa_pollo.html', p: 'Salsa Pollo', f: 'Salsas'},
    ],
    'mpCeb': [
      {d: 'dark_salsa_boletus.html', p: 'Salsa Boletus', f: 'Salsas'},
      {d: 'dark_salsa_tartufata.html', p: 'Salsa Tartufata', f: 'Salsas'},
    ],
    'mpCur': [
      {d: 'dark_pescado.html', p: 'Arroz Pescado', f: 'La Santa'},
    ],
    'mpFilm': [
      {d: 'dark_cremoso_iberico.html', p: 'Cremoso Ibérico', f: 'Cremosos'},
      {d: 'dark_cremoso_queso.html', p: 'Cremoso Queso', f: 'Cremosos'},
      {d: 'dark_cremoso_setas.html', p: 'Cremoso Setas', f: 'Cremosos'},
      {d: 'dark_cremoso_tartufato.html', p: 'Cremoso Tartufato', f: 'Cremosos'},
      {d: 'dark_maestro.html', p: 'Maestro', f: 'Maestro'},
      {d: 'dark_negro.html', p: 'Arroz Negro', f: 'La Santa'},
      {d: 'dark_pescado.html', p: 'Arroz Pescado', f: 'La Santa'},
      {d: 'dark_pollo.html', p: 'Arroz Pollo', f: 'La Santa'},
      {d: 'dark_risotto.html', p: 'Risotto', f: 'La Santa'},
      {d: 'dark_salsa_boletus.html', p: 'Salsa Boletus', f: 'Salsas'},
      {d: 'dark_salsa_iberica.html', p: 'Salsa Ibérico', f: 'Salsas'},
      {d: 'dark_salsa_negra.html', p: 'Salsa Negra', f: 'Salsas'},
      {d: 'dark_salsa_pescado.html', p: 'Salsa Pescado', f: 'Salsas'},
      {d: 'dark_salsa_pollo.html', p: 'Salsa Pollo', f: 'Salsas'},
      {d: 'dark_salsa_queso.html', p: 'Salsa Queso', f: 'Salsas'},
      {d: 'dark_salsa_tartufata.html', p: 'Salsa Tartufata', f: 'Salsas'},
      {d: 'dark_salsa_verduras.html', p: 'Salsa Verduras', f: 'Salsas'},
      {d: 'dark_verduras.html', p: 'Arroz Verduras', f: 'La Santa'},
    ],
    'mpGraPollo': [
      {d: 'dark_cremoso_queso.html', p: 'Cremoso Queso', f: 'Cremosos'},
    ],
    'mpGrasaPollo': [
      {d: 'dark_salsa_iberica.html', p: 'Salsa Ibérico', f: 'Salsas'},
      {d: 'dark_salsa_queso.html', p: 'Salsa Queso', f: 'Salsas'},
      {d: 'dark_salsa_tartufata.html', p: 'Salsa Tartufata', f: 'Salsas'},
    ],
    'mpHazelnut': [
      {d: 'dark_salsa_pollo.html', p: 'Salsa Pollo', f: 'Salsas'},
      {d: 'dark_salsa_tartufata.html', p: 'Salsa Tartufata', f: 'Salsas'},
    ],
    'mpJamon': [
      {d: 'dark_cremoso_iberico.html', p: 'Cremoso Ibérico', f: 'Cremosos'},
    ],
    'mpJerez': [
      {d: 'dark_salsa_queso.html', p: 'Salsa Queso', f: 'Salsas'},
    ],
    'mpMant': [
      {d: 'dark_salsa_boletus.html', p: 'Salsa Boletus', f: 'Salsas'},
      {d: 'dark_salsa_queso.html', p: 'Salsa Queso', f: 'Salsas'},
      {d: 'dark_salsa_tartufata.html', p: 'Salsa Tartufata', f: 'Salsas'},
    ],
    'mpManzanilla': [
      {d: 'dark_salsa_iberica.html', p: 'Salsa Ibérico', f: 'Salsas'},
    ],
    'mpNata': [
      {d: 'dark_salsa_iberica.html', p: 'Salsa Ibérico', f: 'Salsas'},
      {d: 'dark_salsa_queso.html', p: 'Salsa Queso', f: 'Salsas'},
    ],
    'mpParm': [
      {d: 'dark_salsa_boletus.html', p: 'Salsa Boletus', f: 'Salsas'},
      {d: 'dark_salsa_tartufata.html', p: 'Salsa Tartufata', f: 'Salsas'},
    ],
    'mpQuesoAzul': [
      {d: 'dark_salsa_queso.html', p: 'Salsa Queso', f: 'Salsas'},
    ],
    'mpSal': [
      {d: 'dark_cremoso_iberico.html', p: 'Cremoso Ibérico', f: 'Cremosos'},
      {d: 'dark_cremoso_queso.html', p: 'Cremoso Queso', f: 'Cremosos'},
      {d: 'dark_cremoso_setas.html', p: 'Cremoso Setas', f: 'Cremosos'},
      {d: 'dark_cremoso_tartufato.html', p: 'Cremoso Tartufato', f: 'Cremosos'},
      {d: 'dark_negro.html', p: 'Arroz Negro', f: 'La Santa'},
      {d: 'dark_pescado.html', p: 'Arroz Pescado', f: 'La Santa'},
      {d: 'dark_pollo.html', p: 'Arroz Pollo', f: 'La Santa'},
      {d: 'dark_risotto.html', p: 'Risotto', f: 'La Santa'},
      {d: 'dark_salsa_boletus.html', p: 'Salsa Boletus', f: 'Salsas'},
      {d: 'dark_salsa_iberica.html', p: 'Salsa Ibérico', f: 'Salsas'},
      {d: 'dark_salsa_negra.html', p: 'Salsa Negra', f: 'Salsas'},
      {d: 'dark_salsa_pescado.html', p: 'Salsa Pescado', f: 'Salsas'},
      {d: 'dark_salsa_pollo.html', p: 'Salsa Pollo', f: 'Salsas'},
      {d: 'dark_salsa_queso.html', p: 'Salsa Queso', f: 'Salsas'},
      {d: 'dark_salsa_tartufata.html', p: 'Salsa Tartufata', f: 'Salsas'},
      {d: 'dark_verduras.html', p: 'Arroz Verduras', f: 'La Santa'},
    ],
    'mpSalmorreta': [
      {d: 'dark_salsa_negra.html', p: 'Salsa Negra', f: 'Salsas'},
      {d: 'dark_salsa_pescado.html', p: 'Salsa Pescado', f: 'Salsas'},
      {d: 'dark_salsa_pollo.html', p: 'Salsa Pollo', f: 'Salsas'},
    ],
    'mpSalsaVerd': [
      {d: 'dark_salsa_verduras.html', p: 'Salsa Verduras', f: 'Salsas'},
    ],
    'mpTinta': [
      {d: 'dark_salsa_negra.html', p: 'Salsa Negra', f: 'Salsas'},
    ],
    'mpUmami': [
      {d: 'dark_salsa_iberica.html', p: 'Salsa Ibérico', f: 'Salsas'},
      {d: 'dark_salsa_pollo.html', p: 'Salsa Pollo', f: 'Salsas'},
      {d: 'dark_salsa_queso.html', p: 'Salsa Queso', f: 'Salsas'},
      {d: 'dark_salsa_tartufata.html', p: 'Salsa Tartufata', f: 'Salsas'},
    ],
    'mpVino': [
      {d: 'dark_salsa_tartufata.html', p: 'Salsa Tartufata', f: 'Salsas'},
    ],
    'mpXantana': [
      {d: 'dark_salsa_iberica.html', p: 'Salsa Ibérico', f: 'Salsas'},
      {d: 'dark_salsa_queso.html', p: 'Salsa Queso', f: 'Salsas'},
      {d: 'dark_salsa_tartufata.html', p: 'Salsa Tartufata', f: 'Salsas'},
    ],
    'preAjo': [
      {d: 'dark_cremoso_iberico.html', p: 'Cremoso Ibérico', f: 'Cremosos'},
      {d: 'dark_cremoso_queso.html', p: 'Cremoso Queso', f: 'Cremosos'},
      {d: 'dark_cremoso_setas.html', p: 'Cremoso Setas', f: 'Cremosos'},
      {d: 'dark_cremoso_tartufato.html', p: 'Cremoso Tartufato', f: 'Cremosos'},
      {d: 'dark_negro.html', p: 'Arroz Negro', f: 'La Santa'},
      {d: 'dark_pescado.html', p: 'Arroz Pescado', f: 'La Santa'},
      {d: 'dark_pollo.html', p: 'Arroz Pollo', f: 'La Santa'},
      {d: 'dark_risotto.html', p: 'Risotto', f: 'La Santa'},
      {d: 'dark_verduras.html', p: 'Arroz Verduras', f: 'La Santa'},
    ],
    'preAjoM': [
      {d: 'dark_maestro.html', p: 'Maestro', f: 'Maestro'},
    ],
    'preAz': [
      {d: 'dark_maestro.html', p: 'Maestro', f: 'Maestro'},
      {d: 'dark_pescado.html', p: 'Arroz Pescado', f: 'La Santa'},
      {d: 'dark_pollo.html', p: 'Arroz Pollo', f: 'La Santa'},
      {d: 'dark_verduras.html', p: 'Arroz Verduras', f: 'La Santa'},
    ],
    'preNora': [
      {d: 'dark_pescado.html', p: 'Arroz Pescado', f: 'La Santa'},
    ],
    'prePR': [
      {d: 'dark_risotto.html', p: 'Risotto', f: 'La Santa'},
    ],
    'prePV': [
      {d: 'dark_verduras.html', p: 'Arroz Verduras', f: 'La Santa'},
    ],
    'preSalm': [
      {d: 'dark_pollo.html', p: 'Arroz Pollo', f: 'La Santa'},
      {d: 'dark_verduras.html', p: 'Arroz Verduras', f: 'La Santa'},
    ],
    'prepM': [
      {d: 'dark_maestro.html', p: 'Maestro', f: 'Maestro'},
    ],
    // prod, prodRis: excluidos (nodos de producto final, no necesitan "Presente en")
    'salIb': [
      {d: 'dark_cremoso_iberico.html', p: 'Cremoso Ibérico', f: 'Cremosos'},
    ],
    'salQue': [
      {d: 'dark_cremoso_queso.html', p: 'Cremoso Queso', f: 'Cremosos'},
    ],
    'salSet': [
      {d: 'dark_cremoso_setas.html', p: 'Cremoso Setas', f: 'Cremosos'},
    ],
    'salTar': [
      {d: 'dark_cremoso_tartufato.html', p: 'Cremoso Tartufato', f: 'Cremosos'},
    ],
    // salsa: excluido (nodo de proceso genérico, no necesita "Presente en")
  },

  // MP codes to ficha técnica data with PDF file URLs
  fichasTecnicas: {
    'mp01': {nombre: 'Caldo Aneto Pescado', proveedor: 'Aneto', url: 'https://drive.google.com/file/d/18TBLtfQ4ik1TH0Y6cji1UCboLKAWNeSo/view'},
    'mp03': {nombre: 'Paeller Pollo', proveedor: 'Caldos Paeller', url: 'https://drive.google.com/file/d/1wD0-WMNzNnBYgsb5th9b4KKZZgjfJh98/view'},
    'mp04': {nombre: 'Aceite girasol alto oleico', proveedor: 'Coreysa', url: 'https://drive.google.com/file/d/1qGTVaT42QRvtiy7hLia10yrri_2VIJn2/view'},
    'mp05': {nombre: 'Aceite oliva virgen', proveedor: 'Makro', url: 'https://drive.google.com/file/d/1DJ53r7Ea6V1uuoD0vLudoJcEZ1_HydN1/view'},
    'mp06': {nombre: 'Umami', proveedor: 'Givaudan', url: 'https://drive.google.com/file/d/1FWuEgiSON2U5zTEtZgw5hA7CcrXeLe9G/view'},
    'mp07': {nombre: 'Xantana', proveedor: 'Corquimia/Xantana', url: 'https://drive.google.com/file/d/15TM-YoqKEz9X43QxdaShWHpOD0-UHCfM/view'},
    'mp08': {nombre: 'Tinta de sepia', proveedor: 'Nortindal', url: 'https://drive.google.com/file/d/1nh5pmrPNk1o4MOBnp40rby4q0PosJYth/view'},
    'mp09': {nombre: 'Hazelnut (colorante)', proveedor: 'Sensient', url: 'https://drive.google.com/file/d/1zUOHFUdBnWCf41poSeD6NCDivU2eM-lq/view'},
    'mp10': {nombre: 'Pimentón', proveedor: 'Coato', url: 'https://drive.google.com/file/d/1UCZBQpjuP465NEXoJCqOYDbrDSZIjMzk/view'},
    'mp11': {nombre: 'Hierbas (mezcla)', proveedor: 'Expressions Aromatiques', url: 'https://drive.google.com/file/d/14ll7s1GfmtBSzqzVYlEL7j9EP_XThH4A/view'},
    'mp12': {nombre: 'Almidón', proveedor: 'Ingredion', url: 'https://drive.google.com/file/d/1_nvdFmEZ7YQXpcu40GPBsBKbrRnC_S8S/view'},
    'mp13': {nombre: 'Mantequilla', proveedor: 'Presidente/Mantequilla', url: 'https://drive.google.com/file/d/1hDQ3j_ii73QWsyY8sU6d0QjnNcdS-gGK/view'},
    'mp19': {nombre: 'Azafrán', proveedor: 'Verdú Cantó', url: 'https://drive.google.com/file/d/13qJZZXBJNWCZiJnHlife3JOQ9da33xdh/view'},
    'mp20': {nombre: 'Jamón Ibérico', proveedor: 'Enrique Tomás', url: 'https://drive.google.com/file/d/1aqCtokxoNc9xrphXj0DOsl8odKXpssbI/view'},
    'mp21': {nombre: 'Harina Fina de Boletus', proveedor: 'Honza', url: 'https://drive.google.com/file/d/1CfiO_xL_1GGoTTpdqeP_MrrQlHwFpE-c/view'},
    'mp22': {nombre: 'Mezcla Setas con Boletus', proveedor: 'Honza', url: 'https://drive.google.com/file/d/1fROVH-IXDwFurduBS4Ixqj31XGEx09Lq/view'},
    'mp23': {nombre: 'Tartufata pasta trufa', proveedor: 'Solchem', url: 'https://drive.google.com/file/d/1aGRnTNzj5I5be6CT2se7Hca1ZRpPsTpp/view'},
    'mp24': {nombre: 'Arroz Nuovo Maratelli', proveedor: 'Arrocera Pirineo', url: 'https://drive.google.com/file/d/1bd30UpqSM2p8OhSz3h1ByEZ4j_uvvNz_/view'},
    'mp25': {nombre: 'Arroz Bahía', proveedor: 'Illa de Riu', url: ''},
    'mp26': {nombre: 'Arroz Marisma', proveedor: 'Arrozúa', url: ''},
    'mp31': {nombre: 'Ñora en lata', proveedor: 'Rajope', url: 'https://drive.google.com/file/d/1zr-jld0m_C3xzXSclDRvCP636xgglly1/view'},
    'mp33': {nombre: 'Espinaca deshidratada', proveedor: 'La Margarita', url: 'https://drive.google.com/file/d/1B5jyB-Pa6W8xLI8Fzs52BYKCujxaJ7hU/view'},
    'mp34': {nombre: 'Cebolla deshidratada', proveedor: 'Dalmau', url: 'https://drive.google.com/drive/folders/123tPERK4BqmmOFwmLbDyvgTBEa0K5M5v'},
    'mp35': {nombre: 'Pollo deshidratado', proveedor: 'Ugeave', url: 'https://drive.google.com/file/d/10q6pvjD2z1_zQ-3zpd_nJT-9fGtOjKiG/view'},
    'mp36': {nombre: 'Puerro deshidratado', proveedor: 'Dalmau', url: 'https://drive.google.com/drive/folders/123tPERK4BqmmOFwmLbDyvgTBEa0K5M5v'},
    'mp37': {nombre: 'Sal', proveedor: 'Sal', url: 'https://drive.google.com/file/d/1gE2SdBBKl9xAavioR3XOGalsYE6luS7r/view'},
    'mp38': {nombre: 'Ácido tartárico', proveedor: 'SEAH', url: 'https://drive.google.com/file/d/1uRMmbuxE4lKCoJ-PtdfckdotElT8O2Lx/view'},
    'mp39': {nombre: 'Azúcar', proveedor: 'Azucarera', url: 'https://drive.google.com/file/d/1Z3E5Ns1S331LDGLO6sdizdFBqnJIhneK/view'},
    'mp40': {nombre: 'Ajo', proveedor: 'Ajopel', url: 'https://drive.google.com/file/d/1Ojt6683opzmVAHe1PGzC-O2Ppza3CqrF/view'},
    'mp50': {nombre: 'Bandeja EOS-35', proveedor: 'Sarabia', url: 'https://drive.google.com/file/d/1MNeJj9DrWjMgPUv-2w-R7-9mVfcG4sdc/view'},
    'mp51': {nombre: 'Film top-seal', proveedor: 'Adrados', url: 'https://drive.google.com/file/d/1Sd4LLvPNtS3qwsZmy3ElErreIm1UduEe/view'},
    'mp52': {nombre: 'Etiqueta producto', proveedor: '(sin asignar)', url: ''},
    'mp65': {nombre: 'Vino (Manzanilla/Jerez)', proveedor: 'Barbadillo', url: ''},
    'mp66': {nombre: 'Grasa de pollo', proveedor: 'Ugeave', url: 'https://drive.google.com/file/d/1BazN_qRbLRcyvaC8bAPi8Lp0mm3Ypzfo/view'},
    'mp73': {nombre: 'Queso azul', proveedor: 'Queso', url: 'https://drive.google.com/file/d/1hDAwSnqsyEeSAqtPH8AHsvC3MGL00HYy/view'},
    'mpAceite': {nombre: 'Aceite girasol alto oleico', proveedor: 'Coreysa', url: 'https://drive.google.com/file/d/1qGTVaT42QRvtiy7hLia10yrri_2VIJn2/view'},
    'mpAceiteTrufado': {nombre: 'Aceite trufado', proveedor: 'Solchem', url: 'https://drive.google.com/file/d/1aGRnTNzj5I5be6CT2se7Hca1ZRpPsTpp/view'},
    'mpAg': {nombre: 'Agua', proveedor: 'Water', url: ''},
    'mpAgua': {nombre: 'Agua', proveedor: 'Water', url: ''},
    'mpAgua1': {nombre: 'Agua', proveedor: 'Water', url: ''},
    'mpAguaAlmidonada': {nombre: 'Agua almidonada', proveedor: 'Water', url: ''},
    'mpAjo': {nombre: 'Ajo', proveedor: 'Ajopel', url: 'https://drive.google.com/file/d/1Ojt6683opzmVAHe1PGzC-O2Ppza3CqrF/view'},
    'mpArr': {nombre: 'Arroz Bahía', proveedor: 'Arrozúa (temp. ficha Marisma)', url: ''},
    'mpAromaJamon': {nombre: 'Aroma de jamón', proveedor: 'Givaudan', url: 'https://drive.google.com/drive/folders/1HGKb1KAwa8EdQind601XHifbxwpopFnq'},
    'mpAromaQue': {nombre: 'Aroma de queso', proveedor: 'Givaudan', url: 'https://drive.google.com/drive/folders/1HGKb1KAwa8EdQind601XHifbxwpopFnq'},
    'mpAromaQueso': {nombre: 'Aroma de queso', proveedor: 'Givaudan', url: 'https://drive.google.com/drive/folders/1HGKb1KAwa8EdQind601XHifbxwpopFnq'},
    'mpBand': {nombre: 'Bandeja EOS-50', proveedor: 'Sarabia', url: 'https://drive.google.com/file/d/11bHMMjNOQ9aLh5bb-EVWCO1YBYERoCDT/view'},
    'mpCMC': {nombre: 'CMC (carboximetilcelulosa)', proveedor: 'Dalmau', url: 'https://drive.google.com/file/d/1IsVh7rn5T98gSZDVzB3vx2ntk-8kkksL/view'},
    'mpCaldoPescado': {nombre: 'Caldo Pescado prelab.', proveedor: 'Aneto', url: 'https://drive.google.com/file/d/18TBLtfQ4ik1TH0Y6cji1UCboLKAWNeSo/view'},
    'mpCaldoPollo': {nombre: 'Caldo Pollo prelab.', proveedor: 'Caldos Paeller', url: 'https://drive.google.com/file/d/1wD0-WMNzNnBYgsb5th9b4KKZZgjfJh98/view'},
    'mpCeb': {nombre: 'Cebolla deshidratada', proveedor: 'Dalmau', url: 'https://drive.google.com/drive/folders/123tPERK4BqmmOFwmLbDyvgTBEa0K5M5v'},
    'mpCur': {nombre: 'Cúrcuma', proveedor: 'Ajopel', url: 'https://drive.google.com/file/d/1Ojt6683opzmVAHe1PGzC-O2Ppza3CqrF/view'},
    'mpFilm': {nombre: 'Film', proveedor: 'Adrados', url: 'https://drive.google.com/file/d/1Sd4LLvPNtS3qwsZmy3ElErreIm1UduEe/view'},
    'mpGraPollo': {nombre: 'Grasa de pollo', proveedor: 'Ugeave', url: 'https://drive.google.com/file/d/1BazN_qRbLRcyvaC8bAPi8Lp0mm3Ypzfo/view'},
    'mpGrasaPollo': {nombre: 'Grasa de pollo', proveedor: 'Ugeave', url: 'https://drive.google.com/file/d/1BazN_qRbLRcyvaC8bAPi8Lp0mm3Ypzfo/view'},
    'mpHazelnut': {nombre: 'Hazelnut (colorante)', proveedor: 'Sensient', url: 'https://drive.google.com/file/d/1zUOHFUdBnWCf41poSeD6NCDivU2eM-lq/view'},
    'mpJamon': {nombre: 'Jamón', proveedor: 'Enrique Tomás', url: 'https://drive.google.com/file/d/1aqCtokxoNc9xrphXj0DOsl8odKXpssbI/view'},
    'mpJerez': {nombre: 'Vinagre de Jerez', proveedor: 'Makro', url: 'https://drive.google.com/file/d/1L1NeDO7iIHI93HRkFRZ0knPv2J3FzE2r/view'},
    'mpMant': {nombre: 'Mantequilla', proveedor: 'Presidente/Mantequilla', url: 'https://drive.google.com/file/d/1hDQ3j_ii73QWsyY8sU6d0QjnNcdS-gGK/view'},
    'mpManzanilla': {nombre: 'Vino manzanilla', proveedor: 'Makro', url: 'https://drive.google.com/file/d/1YTsaNwQ7YbWKYdZWyY5efhBAQwrBUYD9/view'},
    'mpNata': {nombre: 'Nata', proveedor: 'Makro', url: 'https://drive.google.com/file/d/1v6qwzvADKjQTspRmE-C_e0BYwkE4PYoz/view'},
    'mpParm': {nombre: 'Parmesano rallado', proveedor: 'Queso', url: 'https://drive.google.com/file/d/1hDAwSnqsyEeSAqtPH8AHsvC3MGL00HYy/view'},
    'mpQuesoAzul': {nombre: 'Queso azul', proveedor: 'Queso', url: 'https://drive.google.com/file/d/1hDAwSnqsyEeSAqtPH8AHsvC3MGL00HYy/view'},
    'mpSal': {nombre: 'Sal', proveedor: 'Sal', url: 'https://drive.google.com/file/d/1gE2SdBBKl9xAavioR3XOGalsYE6luS7r/view'},
    'mpSalmorreta': {nombre: 'Salmorreta prelab.', proveedor: 'Preelaboración', url: ''},
    'mpSalsaVerd': {nombre: 'Salsa Verduras prelab.', proveedor: 'Preelaboración', url: ''},
    'mpTinta': {nombre: 'Tinta de sepia', proveedor: 'Nortindal', url: 'https://drive.google.com/file/d/1nh5pmrPNk1o4MOBnp40rby4q0PosJYth/view'},
    'mpUmami': {nombre: 'Umami', proveedor: 'Givaudan', url: 'https://drive.google.com/file/d/1FWuEgiSON2U5zTEtZgw5hA7CcrXeLe9G/view'},
    'mpVino': {nombre: 'Vino blanco', proveedor: 'Makro', url: 'https://drive.google.com/file/d/1YTsaNwQ7YbWKYdZWyY5efhBAQwrBUYD9/view'},
    'mpXantana': {nombre: 'Xantana', proveedor: 'Corquimia/Xantana', url: 'https://drive.google.com/file/d/15TM-YoqKEz9X43QxdaShWHpOD0-UHCfM/view'},
  },

  // Diagram metadata
  diagramas: {
    'dark_pescado.html': {nombre: 'Arroz Pescado', familia: 'La Santa'},
    'dark_negro.html': {nombre: 'Arroz Negro', familia: 'La Santa'},
    'dark_pollo.html': {nombre: 'Arroz Pollo', familia: 'La Santa'},
    'dark_verduras.html': {nombre: 'Arroz Verduras', familia: 'La Santa'},
    'dark_risotto.html': {nombre: 'Risotto', familia: 'La Santa'},
    'dark_cremoso_iberico.html': {nombre: 'Cremoso Ibérico', familia: 'Cremosos'},
    'dark_cremoso_queso.html': {nombre: 'Cremoso Queso', familia: 'Cremosos'},
    'dark_cremoso_setas.html': {nombre: 'Cremoso Setas', familia: 'Cremosos'},
    'dark_cremoso_tartufato.html': {nombre: 'Cremoso Tartufato', familia: 'Cremosos'},
    'dark_salsa_boletus.html': {nombre: 'Salsa Boletus', familia: 'Salsas'},
    'dark_salsa_iberica.html': {nombre: 'Salsa Ibérico', familia: 'Salsas'},
    'dark_salsa_negra.html': {nombre: 'Salsa Negra', familia: 'Salsas'},
    'dark_salsa_pescado.html': {nombre: 'Salsa Pescado', familia: 'Salsas'},
    'dark_salsa_pollo.html': {nombre: 'Salsa Pollo', familia: 'Salsas'},
    'dark_salsa_queso.html': {nombre: 'Salsa Queso', familia: 'Salsas'},
    'dark_salsa_tartufata.html': {nombre: 'Salsa Tartufata', familia: 'Salsas'},
    'dark_salsa_verduras.html': {nombre: 'Salsa Verduras', familia: 'Salsas'},
    'dark_maestro.html': {nombre: 'Maestro', familia: 'Maestro'},
  }
};
