// Cross-reference data for production flow diagram traceability
// Maps node IDs to diagrams, metadata, and ficha técnica URLs

const CROSS_REF = {
  // Node ID → [{d: diagram filename, p: product name, f: family}]
  presenteEn: {
    'bolsa': [
      {d: 'dark_salsa_boletus.html', p: 'Salsa Boletus', f: 'Salsas'},
      {d: 'dark_salsa_iberica.html', p: 'Salsa Ibérico', f: 'Salsas'},
      {d: 'dark_salsa_negra.html', p: 'Salsa Negra', f: 'Salsas'},
      {d: 'dark_salsa_pescado.html', p: 'Salsa Pescado', f: 'Salsas'},
      {d: 'dark_salsa_pollo.html', p: 'Salsa Pollo', f: 'Salsas'},
      {d: 'dark_salsa_queso.html', p: 'Salsa Queso', f: 'Salsas'},
      {d: 'dark_salsa_tartufata.html', p: 'Salsa Tartufata', f: 'Salsas'},
      {d: 'dark_salsa_verduras.html', p: 'Salsa Verduras', f: 'Salsas'},
    ],
    'cajaRis': [
      {d: 'dark_salsa_boletus.html', p: 'Salsa Boletus', f: 'Salsas'},
      {d: 'dark_salsa_iberica.html', p: 'Salsa Ibérico', f: 'Salsas'},
      {d: 'dark_salsa_negra.html', p: 'Salsa Negra', f: 'Salsas'},
      {d: 'dark_salsa_pescado.html', p: 'Salsa Pescado', f: 'Salsas'},
      {d: 'dark_salsa_pollo.html', p: 'Salsa Pollo', f: 'Salsas'},
      {d: 'dark_salsa_queso.html', p: 'Salsa Queso', f: 'Salsas'},
      {d: 'dark_salsa_tartufata.html', p: 'Salsa Tartufata', f: 'Salsas'},
      {d: 'dark_salsa_verduras.html', p: 'Salsa Verduras', f: 'Salsas'},
    ],
    'jarP': [
      {d: 'dark_pescado.html', p: 'Arroz Pescado', f: 'La Santa'},
      {d: 'dark_negro.html', p: 'Arroz Negro', f: 'La Santa'},
      {d: 'dark_pollo.html', p: 'Arroz Pollo', f: 'La Santa'},
    ],
    'jarR': [
      {d: 'dark_cremoso_iberico.html', p: 'Cremoso Ibérico', f: 'All-Included'},
      {d: 'dark_cremoso_queso.html', p: 'Cremoso Queso', f: 'All-Included'},
      {d: 'dark_cremoso_setas.html', p: 'Cremoso Setas', f: 'All-Included'},
      {d: 'dark_cremoso_tartufato.html', p: 'Cremoso Tartufato', f: 'All-Included'},
      {d: 'dark_risotto.html', p: 'Risotto', f: 'La Santa'},
    ],
    'jarV': [
      {d: 'dark_verduras.html', p: 'Arroz Verduras', f: 'La Santa'},
    ],
    'mp01': [
      {d: 'dark_pescado.html', p: 'Arroz Pescado', f: 'La Santa'},
    ],
    'mp03': [
      {d: 'dark_pollo.html', p: 'Arroz Pollo', f: 'La Santa'},
    ],
    'mp04': [
      {d: 'dark_pescado.html', p: 'Arroz Pescado', f: 'La Santa'},
      {d: 'dark_negro.html', p: 'Arroz Negro', f: 'La Santa'},
      {d: 'dark_pollo.html', p: 'Arroz Pollo', f: 'La Santa'},
      {d: 'dark_verduras.html', p: 'Arroz Verduras', f: 'La Santa'},
      {d: 'dark_risotto.html', p: 'Risotto', f: 'La Santa'},
      {d: 'dark_cremoso_iberico.html', p: 'Cremoso Ibérico', f: 'All-Included'},
      {d: 'dark_cremoso_queso.html', p: 'Cremoso Queso', f: 'All-Included'},
      {d: 'dark_cremoso_setas.html', p: 'Cremoso Setas', f: 'All-Included'},
      {d: 'dark_cremoso_tartufato.html', p: 'Cremoso Tartufato', f: 'All-Included'},
      {d: 'dark_salsa_boletus.html', p: 'Salsa Boletus', f: 'Salsas'},
      {d: 'dark_salsa_tartufata.html', p: 'Salsa Tartufata', f: 'Salsas'},
    ],
    'mp05': [
      {d: 'dark_pollo.html', p: 'Arroz Pollo', f: 'La Santa'},
      {d: 'dark_verduras.html', p: 'Arroz Verduras', f: 'La Santa'},
    ],
    'mp06': [
      {d: 'dark_pescado.html', p: 'Arroz Pescado', f: 'La Santa'},
      {d: 'dark_negro.html', p: 'Arroz Negro', f: 'La Santa'},
      {d: 'dark_pollo.html', p: 'Arroz Pollo', f: 'La Santa'},
      {d: 'dark_verduras.html', p: 'Arroz Verduras', f: 'La Santa'},
      {d: 'dark_risotto.html', p: 'Risotto', f: 'La Santa'},
      {d: 'dark_cremoso_iberico.html', p: 'Cremoso Ibérico', f: 'All-Included'},
      {d: 'dark_cremoso_queso.html', p: 'Cremoso Queso', f: 'All-Included'},
      {d: 'dark_cremoso_setas.html', p: 'Cremoso Setas', f: 'All-Included'},
      {d: 'dark_cremoso_tartufato.html', p: 'Cremoso Tartufato', f: 'All-Included'},
      {d: 'dark_salsa_boletus.html', p: 'Salsa Boletus', f: 'Salsas'},
      {d: 'dark_salsa_queso.html', p: 'Salsa Queso', f: 'Salsas'},
      {d: 'dark_salsa_tartufata.html', p: 'Salsa Tartufata', f: 'Salsas'},
      {d: 'dark_maestro.html', p: 'Maestro', f: 'Maestro'},
    ],
    'mp07': [
      {d: 'dark_pescado.html', p: 'Arroz Pescado', f: 'La Santa'},
      {d: 'dark_negro.html', p: 'Arroz Negro', f: 'La Santa'},
      {d: 'dark_pollo.html', p: 'Arroz Pollo', f: 'La Santa'},
      {d: 'dark_verduras.html', p: 'Arroz Verduras', f: 'La Santa'},
      {d: 'dark_risotto.html', p: 'Risotto', f: 'La Santa'},
      {d: 'dark_cremoso_iberico.html', p: 'Cremoso Ibérico', f: 'All-Included'},
      {d: 'dark_cremoso_queso.html', p: 'Cremoso Queso', f: 'All-Included'},
      {d: 'dark_cremoso_setas.html', p: 'Cremoso Setas', f: 'All-Included'},
      {d: 'dark_cremoso_tartufato.html', p: 'Cremoso Tartufato', f: 'All-Included'},
      {d: 'dark_salsa_boletus.html', p: 'Salsa Boletus', f: 'Salsas'},
      {d: 'dark_salsa_queso.html', p: 'Salsa Queso', f: 'Salsas'},
      {d: 'dark_salsa_tartufata.html', p: 'Salsa Tartufata', f: 'Salsas'},
    ],
    'mp08': [
      {d: 'dark_negro.html', p: 'Arroz Negro', f: 'La Santa'},
    ],
    'mp09': [
      {d: 'dark_pescado.html', p: 'Arroz Pescado', f: 'La Santa'},
      {d: 'dark_negro.html', p: 'Arroz Negro', f: 'La Santa'},
      {d: 'dark_pollo.html', p: 'Arroz Pollo', f: 'La Santa'},
      {d: 'dark_verduras.html', p: 'Arroz Verduras', f: 'La Santa'},
      {d: 'dark_risotto.html', p: 'Risotto', f: 'La Santa'},
      {d: 'dark_cremoso_iberico.html', p: 'Cremoso Ibérico', f: 'All-Included'},
      {d: 'dark_cremoso_queso.html', p: 'Cremoso Queso', f: 'All-Included'},
      {d: 'dark_cremoso_setas.html', p: 'Cremoso Setas', f: 'All-Included'},
      {d: 'dark_cremoso_tartufato.html', p: 'Cremoso Tartufato', f: 'All-Included'},
      {d: 'dark_salsa_tartufata.html', p: 'Salsa Tartufata', f: 'Salsas'},
      {d: 'dark_salsa_pollo.html', p: 'Salsa Pollo', f: 'Salsas'},
      {d: 'dark_maestro.html', p: 'Maestro', f: 'Maestro'},
    ],
    'mp10': [
      {d: 'dark_pescado.html', p: 'Arroz Pescado', f: 'La Santa'},
      {d: 'dark_verduras.html', p: 'Arroz Verduras', f: 'La Santa'},
    ],
    'mp11': [
      {d: 'dark_verduras.html', p: 'Arroz Verduras', f: 'La Santa'},
    ],
    'mp12': [
      {d: 'dark_risotto.html', p: 'Risotto', f: 'La Santa'},
      {d: 'dark_cremoso_iberico.html', p: 'Cremoso Ibérico', f: 'All-Included'},
      {d: 'dark_cremoso_queso.html', p: 'Cremoso Queso', f: 'All-Included'},
      {d: 'dark_cremoso_setas.html', p: 'Cremoso Setas', f: 'All-Included'},
      {d: 'dark_cremoso_tartufato.html', p: 'Cremoso Tartufato', f: 'All-Included'},
    ],
    'mp13': [
      {d: 'dark_risotto.html', p: 'Risotto', f: 'La Santa'},
      {d: 'dark_cremoso_iberico.html', p: 'Cremoso Ibérico', f: 'All-Included'},
      {d: 'dark_cremoso_queso.html', p: 'Cremoso Queso', f: 'All-Included'},
      {d: 'dark_cremoso_setas.html', p: 'Cremoso Setas', f: 'All-Included'},
      {d: 'dark_cremoso_tartufato.html', p: 'Cremoso Tartufato', f: 'All-Included'},
      {d: 'dark_salsa_boletus.html', p: 'Salsa Boletus', f: 'Salsas'},
      {d: 'dark_salsa_queso.html', p: 'Salsa Queso', f: 'Salsas'},
      {d: 'dark_salsa_tartufata.html', p: 'Salsa Tartufata', f: 'Salsas'},
    ],
    'mp19': [
      {d: 'dark_pescado.html', p: 'Arroz Pescado', f: 'La Santa'},
      {d: 'dark_pollo.html', p: 'Arroz Pollo', f: 'La Santa'},
      {d: 'dark_verduras.html', p: 'Arroz Verduras', f: 'La Santa'},
      {d: 'dark_cremoso_iberico.html', p: 'Cremoso Ibérico', f: 'All-Included'},
      {d: 'dark_cremoso_queso.html', p: 'Cremoso Queso', f: 'All-Included'},
      {d: 'dark_cremoso_setas.html', p: 'Cremoso Setas', f: 'All-Included'},
      {d: 'dark_cremoso_tartufato.html', p: 'Cremoso Tartufato', f: 'All-Included'},
      {d: 'dark_maestro.html', p: 'Maestro', f: 'Maestro'},
    ],
    'mp20': [
      {d: 'dark_cremoso_iberico.html', p: 'Cremoso Ibérico', f: 'All-Included'},
    ],
    'mp21': [
      {d: 'dark_salsa_boletus.html', p: 'Salsa Boletus', f: 'Salsas'},
    ],
    'mp22': [
      {d: 'dark_cremoso_setas.html', p: 'Cremoso Setas', f: 'All-Included'},
    ],
    'mp23': [
      {d: 'dark_cremoso_tartufato.html', p: 'Cremoso Tartufato', f: 'All-Included'},
    ],
    'mp24': [
      {d: 'dark_pescado.html', p: 'Arroz Pescado', f: 'La Santa'},
      {d: 'dark_negro.html', p: 'Arroz Negro', f: 'La Santa'},
      {d: 'dark_pollo.html', p: 'Arroz Pollo', f: 'La Santa'},
      {d: 'dark_verduras.html', p: 'Arroz Verduras', f: 'La Santa'},
      {d: 'dark_risotto.html', p: 'Risotto', f: 'La Santa'},
      {d: 'dark_cremoso_iberico.html', p: 'Cremoso Ibérico', f: 'All-Included'},
      {d: 'dark_cremoso_queso.html', p: 'Cremoso Queso', f: 'All-Included'},
      {d: 'dark_cremoso_setas.html', p: 'Cremoso Setas', f: 'All-Included'},
      {d: 'dark_cremoso_tartufato.html', p: 'Cremoso Tartufato', f: 'All-Included'},
      {d: 'dark_maestro.html', p: 'Maestro', f: 'Maestro'},
    ],
    'mp31': [
      {d: 'dark_pescado.html', p: 'Arroz Pescado', f: 'La Santa'},
    ],
    'mp33': [
      {d: 'dark_pescado.html', p: 'Arroz Pescado', f: 'La Santa'},
      {d: 'dark_negro.html', p: 'Arroz Negro', f: 'La Santa'},
      {d: 'dark_pollo.html', p: 'Arroz Pollo', f: 'La Santa'},
      {d: 'dark_verduras.html', p: 'Arroz Verduras', f: 'La Santa'},
      {d: 'dark_cremoso_iberico.html', p: 'Cremoso Ibérico', f: 'All-Included'},
      {d: 'dark_cremoso_queso.html', p: 'Cremoso Queso', f: 'All-Included'},
      {d: 'dark_cremoso_setas.html', p: 'Cremoso Setas', f: 'All-Included'},
      {d: 'dark_cremoso_tartufato.html', p: 'Cremoso Tartufato', f: 'All-Included'},
    ],
    'mp34': [
      {d: 'dark_verduras.html', p: 'Arroz Verduras', f: 'La Santa'},
      {d: 'dark_risotto.html', p: 'Risotto', f: 'La Santa'},
      {d: 'dark_salsa_tartufata.html', p: 'Salsa Tartufata', f: 'Salsas'},
    ],
    'mp35': [
      {d: 'dark_pescado.html', p: 'Arroz Pescado', f: 'La Santa'},
      {d: 'dark_negro.html', p: 'Arroz Negro', f: 'La Santa'},
      {d: 'dark_pollo.html', p: 'Arroz Pollo', f: 'La Santa'},
      {d: 'dark_risotto.html', p: 'Risotto', f: 'La Santa'},
      {d: 'dark_cremoso_iberico.html', p: 'Cremoso Ibérico', f: 'All-Included'},
      {d: 'dark_cremoso_queso.html', p: 'Cremoso Queso', f: 'All-Included'},
      {d: 'dark_cremoso_setas.html', p: 'Cremoso Setas', f: 'All-Included'},
      {d: 'dark_cremoso_tartufato.html', p: 'Cremoso Tartufato', f: 'All-Included'},
    ],
    'mp36': [
      {d: 'dark_verduras.html', p: 'Arroz Verduras', f: 'La Santa'},
      {d: 'dark_risotto.html', p: 'Risotto', f: 'La Santa'},
    ],
    'mp38': [
      {d: 'dark_risotto.html', p: 'Risotto', f: 'La Santa'},
      {d: 'dark_maestro.html', p: 'Maestro', f: 'Maestro'},
    ],
    'mp39': [
      {d: 'dark_risotto.html', p: 'Risotto', f: 'La Santa'},
    ],
    'mp52': [
      {d: 'dark_maestro.html', p: 'Maestro', f: 'Maestro'},
    ],
    'mp53': [
      {d: 'dark_maestro.html', p: 'Maestro', f: 'Maestro'},
    ],
    'mp65': [
      {d: 'dark_salsa_boletus.html', p: 'Salsa Boletus', f: 'Salsas'},
    ],
    'mp66': [
      {d: 'dark_salsa_boletus.html', p: 'Salsa Boletus', f: 'Salsas'},
    ],
    'mp73': [
      {d: 'dark_cremoso_queso.html', p: 'Cremoso Queso', f: 'All-Included'},
    ],
    'mezJ': [
      {d: 'dark_pescado.html', p: 'Arroz Pescado', f: 'La Santa'},
      {d: 'dark_negro.html', p: 'Arroz Negro', f: 'La Santa'},
      {d: 'dark_pollo.html', p: 'Arroz Pollo', f: 'La Santa'},
    ],
    'mezJR': [
      {d: 'dark_cremoso_iberico.html', p: 'Cremoso Ibérico', f: 'All-Included'},
      {d: 'dark_cremoso_queso.html', p: 'Cremoso Queso', f: 'All-Included'},
      {d: 'dark_cremoso_setas.html', p: 'Cremoso Setas', f: 'All-Included'},
      {d: 'dark_cremoso_tartufato.html', p: 'Cremoso Tartufato', f: 'All-Included'},
    ],
    'mezR': [
      {d: 'dark_risotto.html', p: 'Risotto', f: 'La Santa'},
    ],
    'mpAceite': [
      {d: 'dark_salsa_queso.html', p: 'Salsa Queso', f: 'Salsas'},
      {d: 'dark_salsa_tartufata.html', p: 'Salsa Tartufata', f: 'Salsas'},
    ],
    'mpAceiteTrufado': [
      {d: 'dark_salsa_tartufata.html', p: 'Salsa Tartufata', f: 'Salsas'},
    ],
    'mpAg': [
      {d: 'dark_pescado.html', p: 'Arroz Pescado', f: 'La Santa'},
      {d: 'dark_negro.html', p: 'Arroz Negro', f: 'La Santa'},
      {d: 'dark_pollo.html', p: 'Arroz Pollo', f: 'La Santa'},
      {d: 'dark_verduras.html', p: 'Arroz Verduras', f: 'La Santa'},
      {d: 'dark_risotto.html', p: 'Risotto', f: 'La Santa'},
      {d: 'dark_cremoso_iberico.html', p: 'Cremoso Ibérico', f: 'All-Included'},
      {d: 'dark_cremoso_queso.html', p: 'Cremoso Queso', f: 'All-Included'},
      {d: 'dark_cremoso_setas.html', p: 'Cremoso Setas', f: 'All-Included'},
      {d: 'dark_cremoso_tartufato.html', p: 'Cremoso Tartufato', f: 'All-Included'},
      {d: 'dark_salsa_pescado.html', p: 'Salsa Pescado', f: 'Salsas'},
      {d: 'dark_salsa_pollo.html', p: 'Salsa Pollo', f: 'Salsas'},
      {d: 'dark_maestro.html', p: 'Maestro', f: 'Maestro'},
    ],
    'mpAgua': [
      {d: 'dark_salsa_pescado.html', p: 'Salsa Pescado', f: 'Salsas'},
      {d: 'dark_salsa_pollo.html', p: 'Salsa Pollo', f: 'Salsas'},
      {d: 'dark_salsa_queso.html', p: 'Salsa Queso', f: 'Salsas'},
    ],
    'mpAgua1': [
      {d: 'dark_salsa_verduras.html', p: 'Salsa Verduras', f: 'Salsas'},
    ],
    'mpAguaAlmidonada': [
      {d: 'dark_salsa_verduras.html', p: 'Salsa Verduras', f: 'Salsas'},
    ],
    'mpAjo': [
      {d: 'dark_pescado.html', p: 'Arroz Pescado', f: 'La Santa'},
      {d: 'dark_negro.html', p: 'Arroz Negro', f: 'La Santa'},
      {d: 'dark_pollo.html', p: 'Arroz Pollo', f: 'La Santa'},
      {d: 'dark_verduras.html', p: 'Arroz Verduras', f: 'La Santa'},
      {d: 'dark_risotto.html', p: 'Risotto', f: 'La Santa'},
      {d: 'dark_cremoso_iberico.html', p: 'Cremoso Ibérico', f: 'All-Included'},
      {d: 'dark_cremoso_queso.html', p: 'Cremoso Queso', f: 'All-Included'},
      {d: 'dark_cremoso_setas.html', p: 'Cremoso Setas', f: 'All-Included'},
      {d: 'dark_cremoso_tartufato.html', p: 'Cremoso Tartufato', f: 'All-Included'},
    ],
    'mpArr': [
      {d: 'dark_maestro.html', p: 'Maestro', f: 'Maestro'},
    ],
    'mpAromaJamon': [
      {d: 'dark_salsa_iberica.html', p: 'Salsa Ibérico', f: 'Salsas'},
    ],
    'mpAromaQueso': [
      {d: 'dark_salsa_queso.html', p: 'Salsa Queso', f: 'Salsas'},
    ],
    'mpBand': [
      {d: 'dark_maestro.html', p: 'Maestro', f: 'Maestro'},
    ],
    'mpCaldoPescado': [
      {d: 'dark_salsa_negra.html', p: 'Salsa Negra', f: 'Salsas'},
      {d: 'dark_salsa_pescado.html', p: 'Salsa Pescado', f: 'Salsas'},
    ],
    'mpCaldoPollo': [
      {d: 'dark_salsa_pollo.html', p: 'Salsa Pollo', f: 'Salsas'},
    ],
    'mpCeb': [
      {d: 'dark_salsa_boletus.html', p: 'Salsa Boletus', f: 'Salsas'},
      {d: 'dark_salsa_tartufata.html', p: 'Salsa Tartufata', f: 'Salsas'},
    ],
    'mpCMC': [
      {d: 'dark_salsa_iberica.html', p: 'Salsa Ibérico', f: 'Salsas'},
      {d: 'dark_salsa_queso.html', p: 'Salsa Queso', f: 'Salsas'},
    ],
    'mpCur': [
      {d: 'dark_pescado.html', p: 'Arroz Pescado', f: 'La Santa'},
    ],
    'mpFilm': [
      {d: 'dark_pescado.html', p: 'Arroz Pescado', f: 'La Santa'},
      {d: 'dark_negro.html', p: 'Arroz Negro', f: 'La Santa'},
      {d: 'dark_pollo.html', p: 'Arroz Pollo', f: 'La Santa'},
      {d: 'dark_verduras.html', p: 'Arroz Verduras', f: 'La Santa'},
      {d: 'dark_risotto.html', p: 'Risotto', f: 'La Santa'},
      {d: 'dark_cremoso_iberico.html', p: 'Cremoso Ibérico', f: 'All-Included'},
      {d: 'dark_cremoso_queso.html', p: 'Cremoso Queso', f: 'All-Included'},
      {d: 'dark_cremoso_setas.html', p: 'Cremoso Setas', f: 'All-Included'},
      {d: 'dark_cremoso_tartufato.html', p: 'Cremoso Tartufato', f: 'All-Included'},
      {d: 'dark_salsa_boletus.html', p: 'Salsa Boletus', f: 'Salsas'},
      {d: 'dark_salsa_iberica.html', p: 'Salsa Ibérico', f: 'Salsas'},
      {d: 'dark_salsa_negra.html', p: 'Salsa Negra', f: 'Salsas'},
      {d: 'dark_salsa_pescado.html', p: 'Salsa Pescado', f: 'Salsas'},
      {d: 'dark_salsa_pollo.html', p: 'Salsa Pollo', f: 'Salsas'},
      {d: 'dark_salsa_queso.html', p: 'Salsa Queso', f: 'Salsas'},
      {d: 'dark_salsa_tartufata.html', p: 'Salsa Tartufata', f: 'Salsas'},
      {d: 'dark_salsa_verduras.html', p: 'Salsa Verduras', f: 'Salsas'},
      {d: 'dark_maestro.html', p: 'Maestro', f: 'Maestro'},
    ],
    'mpGrasaPollo': [
      {d: 'dark_salsa_iberica.html', p: 'Salsa Ibérico', f: 'Salsas'},
      {d: 'dark_salsa_queso.html', p: 'Salsa Queso', f: 'Salsas'},
      {d: 'dark_salsa_tartufata.html', p: 'Salsa Tartufata', f: 'Salsas'},
    ],
    'mpHazelnut': [
      {d: 'dark_salsa_pollo.html', p: 'Salsa Pollo', f: 'Salsas'},
      {d: 'dark_salsa_tartufata.html', p: 'Salsa Tartufata', f: 'Salsas'},
    ],
    'mpJamon': [
      {d: 'dark_cremoso_iberico.html', p: 'Cremoso Ibérico', f: 'All-Included'},
    ],
    'mpJerez': [
      {d: 'dark_salsa_queso.html', p: 'Salsa Queso', f: 'Salsas'},
    ],
    'mpMant': [
      {d: 'dark_salsa_boletus.html', p: 'Salsa Boletus', f: 'Salsas'},
      {d: 'dark_salsa_queso.html', p: 'Salsa Queso', f: 'Salsas'},
      {d: 'dark_salsa_tartufata.html', p: 'Salsa Tartufata', f: 'Salsas'},
    ],
    'mpManzanilla': [
      {d: 'dark_salsa_iberica.html', p: 'Salsa Ibérico', f: 'Salsas'},
    ],
    'mpNata': [
      {d: 'dark_salsa_iberica.html', p: 'Salsa Ibérico', f: 'Salsas'},
      {d: 'dark_salsa_queso.html', p: 'Salsa Queso', f: 'Salsas'},
    ],
    'mpParm': [
      {d: 'dark_salsa_boletus.html', p: 'Salsa Boletus', f: 'Salsas'},
      {d: 'dark_salsa_tartufata.html', p: 'Salsa Tartufata', f: 'Salsas'},
    ],
    'mpPimienta': [
      {d: 'dark_salsa_queso.html', p: 'Salsa Queso', f: 'Salsas'},
    ],
    'mpQuesoAzul': [
      {d: 'dark_salsa_queso.html', p: 'Salsa Queso', f: 'Salsas'},
    ],
    'mpSal': [
      {d: 'dark_pescado.html', p: 'Arroz Pescado', f: 'La Santa'},
      {d: 'dark_negro.html', p: 'Arroz Negro', f: 'La Santa'},
      {d: 'dark_pollo.html', p: 'Arroz Pollo', f: 'La Santa'},
      {d: 'dark_verduras.html', p: 'Arroz Verduras', f: 'La Santa'},
      {d: 'dark_risotto.html', p: 'Risotto', f: 'La Santa'},
      {d: 'dark_cremoso_iberico.html', p: 'Cremoso Ibérico', f: 'All-Included'},
      {d: 'dark_cremoso_queso.html', p: 'Cremoso Queso', f: 'All-Included'},
      {d: 'dark_cremoso_setas.html', p: 'Cremoso Setas', f: 'All-Included'},
      {d: 'dark_cremoso_tartufato.html', p: 'Cremoso Tartufato', f: 'All-Included'},
      {d: 'dark_salsa_boletus.html', p: 'Salsa Boletus', f: 'Salsas'},
      {d: 'dark_salsa_iberica.html', p: 'Salsa Ibérico', f: 'Salsas'},
      {d: 'dark_salsa_negra.html', p: 'Salsa Negra', f: 'Salsas'},
      {d: 'dark_salsa_pescado.html', p: 'Salsa Pescado', f: 'Salsas'},
      {d: 'dark_salsa_pollo.html', p: 'Salsa Pollo', f: 'Salsas'},
      {d: 'dark_salsa_queso.html', p: 'Salsa Queso', f: 'Salsas'},
      {d: 'dark_salsa_tartufata.html', p: 'Salsa Tartufata', f: 'Salsas'},
      {d: 'dark_salsa_verduras.html', p: 'Salsa Verduras', f: 'Salsas'},
    ],
    'mpSalmorreta': [
      {d: 'dark_pollo.html', p: 'Arroz Pollo', f: 'La Santa'},
      {d: 'dark_verduras.html', p: 'Arroz Verduras', f: 'La Santa'},
      {d: 'dark_salsa_negra.html', p: 'Salsa Negra', f: 'Salsas'},
      {d: 'dark_salsa_pescado.html', p: 'Salsa Pescado', f: 'Salsas'},
      {d: 'dark_salsa_pollo.html', p: 'Salsa Pollo', f: 'Salsas'},
    ],
    'mpTinta': [
      {d: 'dark_salsa_negra.html', p: 'Salsa Negra', f: 'Salsas'},
    ],
    'mpUmami': [
      {d: 'dark_salsa_iberica.html', p: 'Salsa Ibérico', f: 'Salsas'},
      {d: 'dark_salsa_pollo.html', p: 'Salsa Pollo', f: 'Salsas'},
      {d: 'dark_salsa_queso.html', p: 'Salsa Queso', f: 'Salsas'},
      {d: 'dark_salsa_tartufata.html', p: 'Salsa Tartufata', f: 'Salsas'},
    ],
    'mpVino': [
      {d: 'dark_salsa_tartufata.html', p: 'Salsa Tartufata', f: 'Salsas'},
    ],
    'mpXantana': [
      {d: 'dark_salsa_iberica.html', p: 'Salsa Ibérico', f: 'Salsas'},
      {d: 'dark_salsa_queso.html', p: 'Salsa Queso', f: 'Salsas'},
      {d: 'dark_salsa_tartufata.html', p: 'Salsa Tartufata', f: 'Salsas'},
    ],
    'preAjo': [
      {d: 'dark_pescado.html', p: 'Arroz Pescado', f: 'La Santa'},
      {d: 'dark_negro.html', p: 'Arroz Negro', f: 'La Santa'},
      {d: 'dark_pollo.html', p: 'Arroz Pollo', f: 'La Santa'},
      {d: 'dark_verduras.html', p: 'Arroz Verduras', f: 'La Santa'},
      {d: 'dark_risotto.html', p: 'Risotto', f: 'La Santa'},
      {d: 'dark_cremoso_iberico.html', p: 'Cremoso Ibérico', f: 'All-Included'},
      {d: 'dark_cremoso_queso.html', p: 'Cremoso Queso', f: 'All-Included'},
      {d: 'dark_cremoso_setas.html', p: 'Cremoso Setas', f: 'All-Included'},
      {d: 'dark_cremoso_tartufato.html', p: 'Cremoso Tartufato', f: 'All-Included'},
    ],
    'preAjoM': [
      {d: 'dark_maestro.html', p: 'Maestro', f: 'Maestro'},
    ],
    'preAz': [
      {d: 'dark_pescado.html', p: 'Arroz Pescado', f: 'La Santa'},
      {d: 'dark_pollo.html', p: 'Arroz Pollo', f: 'La Santa'},
      {d: 'dark_verduras.html', p: 'Arroz Verduras', f: 'La Santa'},
      {d: 'dark_cremoso_iberico.html', p: 'Cremoso Ibérico', f: 'All-Included'},
      {d: 'dark_cremoso_queso.html', p: 'Cremoso Queso', f: 'All-Included'},
      {d: 'dark_cremoso_setas.html', p: 'Cremoso Setas', f: 'All-Included'},
      {d: 'dark_cremoso_tartufato.html', p: 'Cremoso Tartufato', f: 'All-Included'},
      {d: 'dark_maestro.html', p: 'Maestro', f: 'Maestro'},
    ],
    'preNora': [
      {d: 'dark_pescado.html', p: 'Arroz Pescado', f: 'La Santa'},
    ],
    'prePR': [
      {d: 'dark_risotto.html', p: 'Risotto', f: 'La Santa'},
    ],
    'prePV': [
      {d: 'dark_verduras.html', p: 'Arroz Verduras', f: 'La Santa'},
    ],
    'preSalm': [
      {d: 'dark_pollo.html', p: 'Arroz Pollo', f: 'La Santa'},
      {d: 'dark_verduras.html', p: 'Arroz Verduras', f: 'La Santa'},
    ],
    'prepM': [
      {d: 'dark_maestro.html', p: 'Maestro', f: 'Maestro'},
    ],
    'calN': [
      {d: 'dark_negro.html', p: 'Arroz Negro', f: 'La Santa'},
    ],
    'calP': [
      {d: 'dark_pescado.html', p: 'Arroz Pescado', f: 'La Santa'},
    ],
    'calPo': [
      {d: 'dark_pollo.html', p: 'Arroz Pollo', f: 'La Santa'},
    ],
    'calR': [
      {d: 'dark_risotto.html', p: 'Risotto', f: 'La Santa'},
      {d: 'dark_cremoso_iberico.html', p: 'Cremoso Ibérico', f: 'All-Included'},
      {d: 'dark_cremoso_queso.html', p: 'Cremoso Queso', f: 'All-Included'},
      {d: 'dark_cremoso_setas.html', p: 'Cremoso Setas', f: 'All-Included'},
      {d: 'dark_cremoso_tartufato.html', p: 'Cremoso Tartufato', f: 'All-Included'},
    ],
    'calV': [
      {d: 'dark_verduras.html', p: 'Arroz Verduras', f: 'La Santa'},
    ],
    'prod': [
      {d: 'dark_maestro.html', p: 'Maestro', f: 'Maestro'},
    ],
    'prodRis': [
      {d: 'dark_salsa_boletus.html', p: 'Salsa Boletus', f: 'Salsas'},
      {d: 'dark_salsa_iberica.html', p: 'Salsa Ibérico', f: 'Salsas'},
      {d: 'dark_salsa_negra.html', p: 'Salsa Negra', f: 'Salsas'},
      {d: 'dark_salsa_pescado.html', p: 'Salsa Pescado', f: 'Salsas'},
      {d: 'dark_salsa_pollo.html', p: 'Salsa Pollo', f: 'Salsas'},
      {d: 'dark_salsa_queso.html', p: 'Salsa Queso', f: 'Salsas'},
      {d: 'dark_salsa_tartufata.html', p: 'Salsa Tartufata', f: 'Salsas'},
      {d: 'dark_salsa_verduras.html', p: 'Salsa Verduras', f: 'Salsas'},
    ],
    'salIb': [
      {d: 'dark_cremoso_iberico.html', p: 'Cremoso Ibérico', f: 'All-Included'},
    ],
    'salQue': [
      {d: 'dark_cremoso_queso.html', p: 'Cremoso Queso', f: 'All-Included'},
    ],
    'salSet': [
      {d: 'dark_cremoso_setas.html', p: 'Cremoso Setas', f: 'All-Included'},
    ],
    'salTar': [
      {d: 'dark_cremoso_tartufato.html', p: 'Cremoso Tartufato', f: 'All-Included'},
    ],
    'salsa': [
      {d: 'dark_salsa_boletus.html', p: 'Salsa Boletus', f: 'Salsas'},
      {d: 'dark_salsa_iberica.html', p: 'Salsa Ibérico', f: 'Salsas'},
      {d: 'dark_salsa_negra.html', p: 'Salsa Negra', f: 'Salsas'},
      {d: 'dark_salsa_pescado.html', p: 'Salsa Pescado', f: 'Salsas'},
      {d: 'dark_salsa_pollo.html', p: 'Salsa Pollo', f: 'Salsas'},
      {d: 'dark_salsa_queso.html', p: 'Salsa Queso', f: 'Salsas'},
      {d: 'dark_salsa_tartufata.html', p: 'Salsa Tartufata', f: 'Salsas'},
      {d: 'dark_salsa_verduras.html', p: 'Salsa Verduras', f: 'Salsas'},
    ],
    'mpSalsaVerd': [
      {d: 'dark_salsa_verduras.html', p: 'Salsa Verduras', f: 'Salsas'},
    ],
  },

  // MP codes to ficha técnica data (placeholder URLs)
  fichasTecnicas: {
    'mp01': {nombre: 'Caldo Aneto Pescado', proveedor: 'Aneto', url: ''},
    'mp03': {nombre: 'Paeller Pollo', proveedor: 'MP03', url: ''},
    'mp04': {nombre: 'Aceite girasol alto oleico', proveedor: 'Coreysa', url: ''},
    'mp05': {nombre: 'Aceite oliva virgen', proveedor: 'AOVE', url: ''},
    'mp06': {nombre: 'Umami', proveedor: 'Givaudan', url: ''},
    'mp07': {nombre: 'Xantana', proveedor: 'Corquimia', url: ''},
    'mp08': {nombre: 'Tinta de calamar', proveedor: 'MP08', url: ''},
    'mp09': {nombre: 'Hazelnut (colorante)', proveedor: 'Sensient', url: ''},
    'mp10': {nombre: 'Pimentón', proveedor: 'Coato', url: ''},
    'mp11': {nombre: 'Hierbas (mezcla)', proveedor: 'MP11', url: ''},
    'mp12': {nombre: 'Almidón', proveedor: 'MP12', url: ''},
    'mp13': {nombre: 'Mantequilla', proveedor: 'Presidente', url: ''},
    'mp19': {nombre: 'Azafrán', proveedor: 'Verdú Cantó', url: ''},
    'mp20': {nombre: 'Jamón Ibérico', proveedor: 'Enrique Tomás', url: ''},
    'mp21': {nombre: 'Aroma Boletus', proveedor: 'MP21', url: ''},
    'mp22': {nombre: 'Mezcla Setas con Boletus', proveedor: 'Honza', url: ''},
    'mp23': {nombre: 'Tartufata pasta trufa', proveedor: 'Solchem', url: ''},
    'mp24': {nombre: 'Arroz Nuovo Maratelli', proveedor: 'Arrocera del Pirineo', url: ''},
    'mp31': {nombre: 'Ñora en lata', proveedor: 'Rajope', url: ''},
    'mp33': {nombre: 'Espinaca deshidratada', proveedor: 'La Margarita', url: ''},
    'mp34': {nombre: 'Cebolla deshidratada', proveedor: 'MP34', url: ''},
    'mp35': {nombre: 'Pollo deshidratado', proveedor: 'Ugeave', url: ''},
    'mp36': {nombre: 'Puerro deshidratado', proveedor: 'MP36', url: ''},
    'mp37': {nombre: 'Sal', proveedor: 'MP37', url: ''},
    'mp38': {nombre: 'Ácido tartárico', proveedor: 'MP38', url: ''},
    'mp39': {nombre: 'Azúcar', proveedor: 'MP39', url: ''},
    'mp40': {nombre: 'Ajo', proveedor: 'Ajopel', url: ''},
    'mp50': {nombre: 'Bandeja EOS-35', proveedor: 'Sarabia', url: ''},
    'mp51': {nombre: 'Film top-seal', proveedor: 'Adrados', url: ''},
    'mp52': {nombre: 'Salsa Boletus base', proveedor: 'MP52', url: ''},
    'mp53': {nombre: 'Caldo base multiuso', proveedor: 'MP53', url: ''},
    'mp65': {nombre: 'Parmesano rallado', proveedor: 'MP65', url: ''},
    'mp66': {nombre: 'Nata', proveedor: 'MP66', url: ''},
    'mp73': {nombre: 'Queso azul', proveedor: 'Givaudan', url: ''},
    'mpArr': {nombre: 'Arroz', proveedor: 'MP24', url: ''},
    'mpBand': {nombre: 'Bandeja', proveedor: 'Sarabia', url: ''},
    'mpFilm': {nombre: 'Film', proveedor: 'Adrados', url: ''},
    'mpJamon': {nombre: 'Jamón', proveedor: 'Enrique Tomás', url: ''},
    'mpSal': {nombre: 'Sal', proveedor: 'MP37', url: ''},
  },

  // Diagram metadata
  diagramas: {
    'dark_pescado.html': {nombre: 'Arroz Pescado y Marisco', familia: 'La Santa'},
    'dark_negro.html': {nombre: 'Arroz Negro', familia: 'La Santa'},
    'dark_pollo.html': {nombre: 'Arroz Pollo', familia: 'La Santa'},
    'dark_verduras.html': {nombre: 'Arroz Verduras', familia: 'La Santa'},
    'dark_risotto.html': {nombre: 'Risotto', familia: 'La Santa'},
    'dark_cremoso_iberico.html': {nombre: 'Cremoso Ibérico', familia: 'All-Included'},
    'dark_cremoso_queso.html': {nombre: 'Cremoso Queso', familia: 'All-Included'},
    'dark_cremoso_setas.html': {nombre: 'Cremoso Setas', familia: 'All-Included'},
    'dark_cremoso_tartufato.html': {nombre: 'Cremoso Tartufato', familia: 'All-Included'},
    'dark_salsa_boletus.html': {nombre: 'Salsa Boletus', familia: 'Salsas'},
    'dark_salsa_iberica.html': {nombre: 'Salsa Ibérico', familia: 'Salsas'},
    'dark_salsa_negra.html': {nombre: 'Salsa Negra', familia: 'Salsas'},
    'dark_salsa_pescado.html': {nombre: 'Salsa Pescado', familia: 'Salsas'},
    'dark_salsa_pollo.html': {nombre: 'Salsa Pollo', familia: 'Salsas'},
    'dark_salsa_queso.html': {nombre: 'Salsa Queso', familia: 'Salsas'},
    'dark_salsa_tartufata.html': {nombre: 'Salsa Tartufata', familia: 'Salsas'},
    'dark_salsa_verduras.html': {nombre: 'Salsa Verduras', familia: 'Salsas'},
    'dark_maestro.html': {nombre: 'Maestro', familia: 'Maestro'},
  }
};
